// Generated by scripts/generate-public-enterprise-hub-fixture.mjs — do not edit by hand.
// Read from the public-enterprise, entity, company and procurement API on 2026-10-07.
import type { PublicEnterpriseHubSnapshot } from './hub-snapshot-types'

export const PUBLIC_ENTERPRISE_HUB_SNAPSHOT: PublicEnterpriseHubSnapshot = {
  "generatedAt": "2026-10-07T16:47:56.800Z",
  "sources": [
    {
      "family": "amepip",
      "laneStatus": "available",
      "sourceUrl": "https://data.gov.ro/dataset/5a4d4fdb-1e06-4ea6-a3b5-aef01ebba168/resource/8865d8b1-e5db-4a14-8721-9048af14cafe/download/datecompanii_ind-finnefin.xlsx",
      "observedAt": "2026-06-18T19:46:38.921000Z",
      "sourceLastModifiedAt": "2026-01-13T14:23:50.041841Z"
    },
    {
      "family": "s1001",
      "laneStatus": "partial",
      "sourceUrl": "http://static.anaf.ro/static/10/Anaf/Declaratii_R/S1001/Lista%20finala%20a%20IP%20care%20aplica%20OMFP%202873%20si%202874%20%2026%20august%202026%20.pdf",
      "observedAt": "2026-10-06T17:29:46.914000Z",
      "sourceLastModifiedAt": null
    },
    {
      "family": "json_apt",
      "laneStatus": "partial",
      "sourceUrl": "https://amepip.gov.ro/anunturi-de-selectie/",
      "observedAt": "2026-10-06T17:40:39.472000Z",
      "sourceLastModifiedAt": null
    }
  ],
  "members": {
    "anchors": 1743,
    "current": 1721,
    "historical": 22
  },
  "control": {
    "central": 334,
    "local": 1360,
    "noS1001": 27,
    "s1001Authorities": 922,
    "s1001AuthoritiesWithBudget": 863,
    "disagreements": 27,
    "kinds": [
      {
        "kind": "commune",
        "level": "local",
        "enterprises": 684
      },
      {
        "kind": "municipality",
        "level": "local",
        "enterprises": 320
      },
      {
        "kind": "town",
        "level": "local",
        "enterprises": 183
      },
      {
        "kind": "central_authority",
        "level": "central",
        "enterprises": 134
      },
      {
        "kind": "public_entity",
        "level": "central",
        "enterprises": 116
      },
      {
        "kind": "county",
        "level": "local",
        "enterprises": 100
      },
      {
        "kind": "unresolved",
        "level": "local",
        "enterprises": 57
      },
      {
        "kind": "education",
        "level": "central",
        "enterprises": 50
      },
      {
        "kind": "unresolved",
        "level": "central",
        "enterprises": 34
      },
      {
        "kind": "sector",
        "level": "local",
        "enterprises": 16
      }
    ],
    "ranking": {
      "central": [
        {
          "cui": "11795573",
          "name": "AUTORITATEA PENTRU ADMINISTRAREA ACTIVELOR STATULUI",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 69,
          "inactive": 56
        },
        {
          "cui": "24931499",
          "name": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 60,
          "inactive": 18
        },
        {
          "cui": "13729380",
          "name": "MINISTERUL EDUCATIEI SI CERCETARII",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 50,
          "inactive": 0
        },
        {
          "cui": "43507695",
          "name": "MINISTERUL ENERGIEI",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 33,
          "inactive": 10
        },
        {
          "cui": "14818116",
          "name": "AGENTIA DOMENIILOR STATULUI",
          "nameSource": "s1001",
          "level": "central",
          "county": null,
          "hasBudget": false,
          "enterprises": 32,
          "inactive": 30
        },
        {
          "cui": "13633330",
          "name": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 30,
          "inactive": 4
        },
        {
          "cui": "16335444",
          "name": "MINISTERUL MEDIULUI, APELOR SI PADURILOR",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 27,
          "inactive": 0
        },
        {
          "cui": "4283422",
          "name": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 8,
          "inactive": 0
        },
        {
          "cui": "4266669",
          "name": "MINISTERUL MUNCII, FAMILIEI, TINERETULUI Bucuresti SI SOLIDARITATII SOCIALE",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 0
        },
        {
          "cui": "11424532",
          "name": "MINISTERUL APARARII NATIONALE",
          "nameSource": "s1001",
          "level": "central",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 3,
          "inactive": 1
        }
      ],
      "county": [
        {
          "cui": "2540929",
          "name": "CONSILIUL JUDETEAN VALCEA",
          "nameSource": "s1001",
          "level": "local",
          "county": "VÂLCEA",
          "hasBudget": true,
          "enterprises": 8,
          "inactive": 1
        },
        {
          "cui": "4288110",
          "name": "CONSILIUL JUDETEAN CLUJ",
          "nameSource": "s1001",
          "level": "local",
          "county": "CLUJ",
          "hasBudget": true,
          "enterprises": 7,
          "inactive": 3
        },
        {
          "cui": "4417150",
          "name": "CONSILIUL JUDETEAN DOLJ",
          "nameSource": "s1001",
          "level": "local",
          "county": "DOLJ",
          "hasBudget": true,
          "enterprises": 5,
          "inactive": 0
        },
        {
          "cui": "2842889",
          "name": "CONSILIUL JUDETEAN PRAHOVA",
          "nameSource": "s1001",
          "level": "local",
          "county": "PRAHOVA",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 0
        },
        {
          "cui": "4229512",
          "name": "CONSILIUL JUDETEAN ARGES",
          "nameSource": "s1001",
          "level": "local",
          "county": "ARGEȘ",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 0
        },
        {
          "cui": "4280205",
          "name": "CONSILIUL JUDETEAN DAMBOVITA",
          "nameSource": "s1001",
          "level": "local",
          "county": "DÂMBOVIȚA",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 0
        },
        {
          "cui": "4384150",
          "name": "CONSILIUL JUDETEAN BRASOV",
          "nameSource": "s1001",
          "level": "local",
          "county": "BRAȘOV",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 1
        },
        {
          "cui": "4562583",
          "name": "CONSILIUL JUDETEAN ALBA",
          "nameSource": "s1001",
          "level": "local",
          "county": "ALBA",
          "hasBudget": true,
          "enterprises": 4,
          "inactive": 1
        },
        {
          "cui": "2612839",
          "name": "CONSILIUL JUDETEAN NEAMT",
          "nameSource": "s1001",
          "level": "local",
          "county": "NEAMȚ",
          "hasBudget": true,
          "enterprises": 3,
          "inactive": 0
        },
        {
          "cui": "3627315",
          "name": "CONSILIUL JUDETEAN MARAMURES",
          "nameSource": "s1001",
          "level": "local",
          "county": "MARAMUREȘ",
          "hasBudget": true,
          "enterprises": 3,
          "inactive": 0
        }
      ],
      "local": [
        {
          "cui": "4267117",
          "name": "CONSILIUL GENERAL AL MUNICIPIULUI BUCURESTI",
          "nameSource": "s1001",
          "level": "local",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 21,
          "inactive": 13
        },
        {
          "cui": "4283481",
          "name": "CONSILIUL LOCAL VOLUNTARI",
          "nameSource": "s1001",
          "level": "local",
          "county": "ILFOV",
          "hasBudget": true,
          "enterprises": 16,
          "inactive": 0
        },
        {
          "cui": "14756536",
          "name": "CONSILIUL LOCAL TIMISOARA",
          "nameSource": "s1001",
          "level": "local",
          "county": "TIMIȘ",
          "hasBudget": true,
          "enterprises": 10,
          "inactive": 1
        },
        {
          "cui": "4652660",
          "name": "CONSILIUL LOCAL ALEXANDRIA",
          "nameSource": "s1001",
          "level": "local",
          "county": "TELEORMAN",
          "hasBudget": true,
          "enterprises": 10,
          "inactive": 5
        },
        {
          "cui": "3228764",
          "name": "CONSILIUL LOCAL RESITA",
          "nameSource": "s1001",
          "level": "local",
          "county": "CARAȘ-SEVERIN",
          "hasBudget": true,
          "enterprises": 9,
          "inactive": 3
        },
        {
          "cui": "4541580",
          "name": "CONSILIUL LOCAL IASI",
          "nameSource": "s1001",
          "level": "local",
          "county": "IAȘI",
          "hasBudget": true,
          "enterprises": 9,
          "inactive": 2
        },
        {
          "cui": "4404605",
          "name": "CONSILIUL LOCAL SFANTUL GHEORGHE",
          "nameSource": "s1001",
          "level": "local",
          "county": "COVASNA",
          "hasBudget": true,
          "enterprises": 8,
          "inactive": 0
        },
        {
          "cui": "4420465",
          "name": "CONSILIUL LOCAL AL SECTORULUI BUCURESTI",
          "nameSource": "s1001",
          "level": "local",
          "county": "MUNICIPIUL BUCUREȘTI",
          "hasBudget": true,
          "enterprises": 8,
          "inactive": 2
        },
        {
          "cui": "4852455",
          "name": "CONSILIUL LOCAL GIURGIU",
          "nameSource": "s1001",
          "level": "local",
          "county": "GIURGIU",
          "hasBudget": true,
          "enterprises": 8,
          "inactive": 2
        },
        {
          "cui": "3814810",
          "name": "CONSILIUL LOCAL GALATI",
          "nameSource": "s1001",
          "level": "local",
          "county": "GALAȚI",
          "hasBudget": true,
          "enterprises": 7,
          "inactive": 1
        }
      ]
    }
  },
  "status": {
    "s1001": [
      {
        "status": "ACTIV",
        "enterprises": 1420
      },
      {
        "status": "INACTIV",
        "enterprises": 274
      }
    ],
    "s1001NotListed": 27,
    "onrc": [
      {
        "status": "funcțiune",
        "enterprises": 891
      },
      {
        "status": null,
        "enterprises": 742
      },
      {
        "status": "radiată",
        "enterprises": 38
      },
      {
        "status": "dizolvare",
        "enterprises": 17
      },
      {
        "status": "lichidare",
        "enterprises": 11
      },
      {
        "status": "întrerupere temporară de activitate",
        "enterprises": 9
      },
      {
        "status": "faliment",
        "enterprises": 4
      },
      {
        "status": "1083",
        "enterprises": 3
      },
      {
        "status": "1139",
        "enterprises": 3
      },
      {
        "status": "1120",
        "enterprises": 1
      }
    ],
    "onrcMissing": 2,
    "anafInactive": 286,
    "crossings": {
      "radiatedButS1001Active": 18,
      "fiscallyInactiveButS1001Active": 179
    },
    "amepip": [
      {
        "status": "funcţiune",
        "enterprises": 1098
      },
      {
        "status": "întrerupere temporară de activitate",
        "enterprises": 21
      },
      {
        "status": "este sub incidenţa Legii nr. 85/2014, insolvenţă",
        "enterprises": 11
      },
      {
        "status": "este sub incidenţa Legii nr. 85/2014, faliment",
        "enterprises": 7
      },
      {
        "status": "funcţiune, reorganizare - fuziune prin absorbţie",
        "enterprises": 6
      },
      {
        "status": "este sub incidenţa Legii nr. 85/2014, reorganizare judiciară",
        "enterprises": 4
      },
      {
        "status": "lichidare",
        "enterprises": 4
      },
      {
        "status": "dizolvare",
        "enterprises": 3
      },
      {
        "status": "este sub incidenţa Legii nr. 85/2006, reorganizare judiciară",
        "enterprises": 2
      },
      {
        "status": "radiată",
        "enterprises": 2
      },
      {
        "status": "este sub incidenţa Legii nr. 85/2014",
        "enterprises": 1
      },
      {
        "status": "funcţiune, lichidare",
        "enterprises": 1
      },
      {
        "status": "reorganizare - divizare partială",
        "enterprises": 1
      }
    ],
    "amepipMissing": 560
  },
  "counties": [
    {
      "county": "București",
      "total": 162,
      "central": 118,
      "local": 40,
      "none": 4
    },
    {
      "county": "Bihor",
      "total": 79,
      "central": 6,
      "local": 73,
      "none": 0
    },
    {
      "county": "Constanța",
      "total": 75,
      "central": 25,
      "local": 49,
      "none": 1
    },
    {
      "county": "Brașov",
      "total": 74,
      "central": 17,
      "local": 57,
      "none": 0
    },
    {
      "county": "Dolj",
      "total": 71,
      "central": 4,
      "local": 65,
      "none": 2
    },
    {
      "county": "Ilfov",
      "total": 68,
      "central": 16,
      "local": 52,
      "none": 0
    },
    {
      "county": "Timiș",
      "total": 64,
      "central": 10,
      "local": 53,
      "none": 1
    },
    {
      "county": "Teleorman",
      "total": 63,
      "central": 2,
      "local": 60,
      "none": 1
    },
    {
      "county": "Olt",
      "total": 56,
      "central": 1,
      "local": 55,
      "none": 0
    },
    {
      "county": "Prahova",
      "total": 55,
      "central": 9,
      "local": 44,
      "none": 2
    },
    {
      "county": "Argeș",
      "total": 52,
      "central": 5,
      "local": 47,
      "none": 0
    },
    {
      "county": "Cluj",
      "total": 50,
      "central": 9,
      "local": 41,
      "none": 0
    },
    {
      "county": "Caraș-Severin",
      "total": 48,
      "central": 8,
      "local": 40,
      "none": 0
    },
    {
      "county": "Hunedoara",
      "total": 48,
      "central": 10,
      "local": 38,
      "none": 0
    },
    {
      "county": "Gorj",
      "total": 44,
      "central": 7,
      "local": 37,
      "none": 0
    },
    {
      "county": "Harghita",
      "total": 42,
      "central": 3,
      "local": 39,
      "none": 0
    },
    {
      "county": "Arad",
      "total": 41,
      "central": 7,
      "local": 33,
      "none": 1
    },
    {
      "county": "Giurgiu",
      "total": 40,
      "central": 4,
      "local": 36,
      "none": 0
    },
    {
      "county": "Sibiu",
      "total": 36,
      "central": 4,
      "local": 31,
      "none": 1
    },
    {
      "county": "Iași",
      "total": 35,
      "central": 12,
      "local": 23,
      "none": 0
    },
    {
      "county": "Tulcea",
      "total": 33,
      "central": 3,
      "local": 30,
      "none": 0
    },
    {
      "county": "Vâlcea",
      "total": 32,
      "central": 4,
      "local": 27,
      "none": 1
    },
    {
      "county": "Buzău",
      "total": 28,
      "central": 0,
      "local": 27,
      "none": 1
    },
    {
      "county": "Ialomița",
      "total": 28,
      "central": 1,
      "local": 25,
      "none": 2
    },
    {
      "county": "Alba",
      "total": 27,
      "central": 11,
      "local": 16,
      "none": 0
    },
    {
      "county": "Maramureș",
      "total": 27,
      "central": 4,
      "local": 23,
      "none": 0
    },
    {
      "county": "Bistrița-Năsăud",
      "total": 25,
      "central": 1,
      "local": 24,
      "none": 0
    },
    {
      "county": "Călărași",
      "total": 25,
      "central": 4,
      "local": 21,
      "none": 0
    },
    {
      "county": "Covasna",
      "total": 24,
      "central": 0,
      "local": 23,
      "none": 1
    },
    {
      "county": "Neamț",
      "total": 24,
      "central": 3,
      "local": 21,
      "none": 0
    },
    {
      "county": "Satu Mare",
      "total": 24,
      "central": 1,
      "local": 22,
      "none": 1
    },
    {
      "county": "Vrancea",
      "total": 24,
      "central": 1,
      "local": 21,
      "none": 2
    },
    {
      "county": "Dâmbovița",
      "total": 23,
      "central": 5,
      "local": 18,
      "none": 0
    },
    {
      "county": "Bacău",
      "total": 22,
      "central": 1,
      "local": 21,
      "none": 0
    },
    {
      "county": "Mehedinți",
      "total": 22,
      "central": 2,
      "local": 20,
      "none": 0
    },
    {
      "county": "Galați",
      "total": 21,
      "central": 3,
      "local": 18,
      "none": 0
    },
    {
      "county": "Mureș",
      "total": 19,
      "central": 1,
      "local": 17,
      "none": 1
    },
    {
      "county": "Suceava",
      "total": 19,
      "central": 2,
      "local": 17,
      "none": 0
    },
    {
      "county": "Vaslui",
      "total": 16,
      "central": 0,
      "local": 15,
      "none": 1
    },
    {
      "county": "Botoșani",
      "total": 15,
      "central": 0,
      "local": 15,
      "none": 0
    },
    {
      "county": null,
      "total": 14,
      "central": 9,
      "local": 3,
      "none": 2
    },
    {
      "county": "Brăila",
      "total": 13,
      "central": 1,
      "local": 12,
      "none": 0
    },
    {
      "county": "Sălaj",
      "total": 13,
      "central": 0,
      "local": 11,
      "none": 2
    }
  ],
  "sectors": [
    {
      "division": "36",
      "total": 350,
      "central": 2,
      "local": 345,
      "none": 3
    },
    {
      "division": "81",
      "total": 167,
      "central": 0,
      "local": 164,
      "none": 3
    },
    {
      "division": "38",
      "total": 148,
      "central": 0,
      "local": 145,
      "none": 3
    },
    {
      "division": "68",
      "total": 106,
      "central": 7,
      "local": 97,
      "none": 2
    },
    {
      "division": "49",
      "total": 99,
      "central": 9,
      "local": 88,
      "none": 2
    },
    {
      "division": "35",
      "total": 90,
      "central": 16,
      "local": 73,
      "none": 1
    },
    {
      "division": "02",
      "total": 87,
      "central": 23,
      "local": 63,
      "none": 1
    },
    {
      "division": "41",
      "total": 71,
      "central": 1,
      "local": 69,
      "none": 1
    },
    {
      "division": "42",
      "total": 68,
      "central": 2,
      "local": 66,
      "none": 0
    },
    {
      "division": "72",
      "total": 52,
      "central": 52,
      "local": 0,
      "none": 0
    },
    {
      "division": "52",
      "total": 38,
      "central": 16,
      "local": 22,
      "none": 0
    },
    {
      "division": null,
      "total": 37,
      "central": 35,
      "local": 2,
      "none": 0
    },
    {
      "division": "43",
      "total": 31,
      "central": 4,
      "local": 27,
      "none": 0
    },
    {
      "division": "01",
      "total": 25,
      "central": 17,
      "local": 8,
      "none": 0
    },
    {
      "division": "80",
      "total": 25,
      "central": 1,
      "local": 24,
      "none": 0
    },
    {
      "division": "25",
      "total": 18,
      "central": 16,
      "local": 2,
      "none": 0
    },
    {
      "division": "84",
      "total": 18,
      "central": 3,
      "local": 15,
      "none": 0
    },
    {
      "division": "93",
      "total": 18,
      "central": 0,
      "local": 18,
      "none": 0
    },
    {
      "division": "56",
      "total": 14,
      "central": 1,
      "local": 13,
      "none": 0
    },
    {
      "division": "71",
      "total": 13,
      "central": 6,
      "local": 6,
      "none": 1
    },
    {
      "division": "37",
      "total": 12,
      "central": 0,
      "local": 12,
      "none": 0
    },
    {
      "division": "55",
      "total": 11,
      "central": 5,
      "local": 5,
      "none": 1
    },
    {
      "division": "82",
      "total": 10,
      "central": 1,
      "local": 9,
      "none": 0
    },
    {
      "division": "51",
      "total": 9,
      "central": 7,
      "local": 1,
      "none": 1
    },
    {
      "division": "96",
      "total": 9,
      "central": 0,
      "local": 9,
      "none": 0
    },
    {
      "division": "07",
      "total": 8,
      "central": 8,
      "local": 0,
      "none": 0
    },
    {
      "division": "61",
      "total": 8,
      "central": 3,
      "local": 5,
      "none": 0
    },
    {
      "division": "64",
      "total": 8,
      "central": 3,
      "local": 0,
      "none": 5
    },
    {
      "division": "70",
      "total": 8,
      "central": 3,
      "local": 5,
      "none": 0
    },
    {
      "division": "10",
      "total": 7,
      "central": 1,
      "local": 6,
      "none": 0
    },
    {
      "division": "20",
      "total": 7,
      "central": 7,
      "local": 0,
      "none": 0
    },
    {
      "division": "46",
      "total": 7,
      "central": 3,
      "local": 4,
      "none": 0
    },
    {
      "division": "23",
      "total": 6,
      "central": 1,
      "local": 5,
      "none": 0
    },
    {
      "division": "30",
      "total": 6,
      "central": 6,
      "local": 0,
      "none": 0
    },
    {
      "division": "33",
      "total": 6,
      "central": 6,
      "local": 0,
      "none": 0
    },
    {
      "division": "47",
      "total": 6,
      "central": 3,
      "local": 3,
      "none": 0
    },
    {
      "division": "50",
      "total": 6,
      "central": 2,
      "local": 4,
      "none": 0
    },
    {
      "division": "58",
      "total": 6,
      "central": 5,
      "local": 1,
      "none": 0
    },
    {
      "division": "86",
      "total": 6,
      "central": 1,
      "local": 5,
      "none": 0
    },
    {
      "division": "91",
      "total": 6,
      "central": 1,
      "local": 5,
      "none": 0
    },
    {
      "division": "94",
      "total": 6,
      "central": 0,
      "local": 5,
      "none": 1
    },
    {
      "division": "15",
      "total": 5,
      "central": 4,
      "local": 1,
      "none": 0
    },
    {
      "division": "18",
      "total": 5,
      "central": 5,
      "local": 0,
      "none": 0
    },
    {
      "division": "24",
      "total": 5,
      "central": 5,
      "local": 0,
      "none": 0
    },
    {
      "division": "62",
      "total": 5,
      "central": 3,
      "local": 2,
      "none": 0
    },
    {
      "division": "08",
      "total": 4,
      "central": 2,
      "local": 2,
      "none": 0
    },
    {
      "division": "09",
      "total": 4,
      "central": 4,
      "local": 0,
      "none": 0
    },
    {
      "division": "60",
      "total": 4,
      "central": 1,
      "local": 3,
      "none": 0
    },
    {
      "division": "75",
      "total": 4,
      "central": 0,
      "local": 4,
      "none": 0
    },
    {
      "division": "14",
      "total": 3,
      "central": 1,
      "local": 2,
      "none": 0
    },
    {
      "division": "28",
      "total": 3,
      "central": 3,
      "local": 0,
      "none": 0
    },
    {
      "division": "40",
      "total": 3,
      "central": 0,
      "local": 3,
      "none": 0
    },
    {
      "division": "73",
      "total": 3,
      "central": 2,
      "local": 1,
      "none": 0
    },
    {
      "division": "77",
      "total": 3,
      "central": 0,
      "local": 3,
      "none": 0
    },
    {
      "division": "79",
      "total": 3,
      "central": 2,
      "local": 1,
      "none": 0
    },
    {
      "division": "90",
      "total": 3,
      "central": 0,
      "local": 3,
      "none": 0
    },
    {
      "division": "03",
      "total": 2,
      "central": 1,
      "local": 0,
      "none": 1
    },
    {
      "division": "11",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "13",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "21",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "26",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "27",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "32",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "45",
      "total": 2,
      "central": 0,
      "local": 2,
      "none": 0
    },
    {
      "division": "59",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "74",
      "total": 2,
      "central": 2,
      "local": 0,
      "none": 0
    },
    {
      "division": "06",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "31",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "53",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "63",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "65",
      "total": 1,
      "central": 0,
      "local": 0,
      "none": 1
    },
    {
      "division": "66",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "69",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "85",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "87",
      "total": 1,
      "central": 0,
      "local": 1,
      "none": 0
    },
    {
      "division": "92",
      "total": 1,
      "central": 1,
      "local": 0,
      "none": 0
    },
    {
      "division": "95",
      "total": 1,
      "central": 0,
      "local": 1,
      "none": 0
    }
  ],
  "financials": {
    "year": 2024,
    "filed": 1421,
    "publishers": [
      "anaf"
    ],
    "nextYearFiled": 1325,
    "netReported": 1386,
    "loss": 439,
    "implausibleEmployees": [],
    "largest": {
      "turnover": [
        {
          "cui": "13267213",
          "name": "SOCIETATEA DE PRODUCERE A ENERGIEI ELECTRICE IN HIDROCENTRALE  HIDROELECTRICA S.A.",
          "value": "9659879145",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13328043",
          "name": "COMPANIA NATIONALA DE TRANSPORT AL ENERGIEI ELECTRICE TRANSELECTRICA SA",
          "value": "7639092966",
          "authority": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "14056826",
          "name": "SOCIETATEA NATIONALA DE GAZE NATURALE  ROMGAZ  SA",
          "value": "7531970469",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "10874881",
          "name": "SOCIETATEA NATIONALA NUCLEARELECTRICA SA",
          "value": "4680533991",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "11054545",
          "name": "SOCIETATEA NATIONALA DE TRANSPORT FEROVIAR DE CALATORI - CFR - CALATORI SA",
          "value": "3486819881",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "30267310",
          "name": "SOCIETATEA COMPLEXUL ENERGETIC OLTENIA S.A.",
          "value": "3266120740",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1590120",
          "name": "REGIA NATIONALA A PADURILOR ROMSILVA RA",
          "value": "2986336165",
          "authority": "MINISTERUL MEDIULUI, APELOR SI PADURILOR",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "15189596",
          "name": "ELECTROCENTRALE BUCURESTI SA",
          "value": "2506399064",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "41269473",
          "name": "COMPANIA MUNICIPALĂ TERMOENERGETICA BUCUREŞTI S.A.",
          "value": "2299216758",
          "authority": "ASOCIATIA DE DEZVOLTARE INTRACOMUNITARA TERMOENERGETICA BUCURESTI-ILFOV",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13068733",
          "name": "SOCIETATEA NAŢIONALĂ DE TRANSPORT GAZE NATURALE TRANSGAZ SA",
          "value": "2212225271",
          "authority": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "16054368",
          "name": "COMPANIA NAŢIONALĂ DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
          "value": "2019261859",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "427410",
          "name": "COMPANIA NATIONALA POSTA ROMANA SA",
          "value": "1718832902",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1589886",
          "name": "SOCIETATEA DE TRANSPORT BUCUREŞTI STB S.A.",
          "value": "1692481412",
          "authority": "CONSILIUL GENERAL AL MUNICIPIULUI BUCURESTI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1589932",
          "name": "ADMINISTRATIA ROMANA A SERVICIILOR DE TRAFIC AERIAN ROMATSA RA",
          "value": "1632295189",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "26490194",
          "name": "COMPANIA NATIONALA AEROPORTURI BUCURESTI SA",
          "value": "1383970846",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "12397185",
          "name": "COMPANIA NATIONALA LOTERIA ROMANA SA",
          "value": "1291086094",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "477647",
          "name": "COMPANIA NATIONALA DE TRANSPORTURI AERIENE ROMANE TAROM SA",
          "value": "1226498739",
          "authority": null,
          "authorityNameSource": null
        },
        {
          "cui": "11054529",
          "name": "COMPANIA NATIONALA DE CAI FERATE CFR SA",
          "value": "1209451651",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13863739",
          "name": "METROREX SA",
          "value": "1166476200",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "472771",
          "name": "COMPANIA NATIONALA ROMTEHNICA SA",
          "value": "860381791",
          "authority": "MINISTERUL APARARII NATIONALE",
          "authorityNameSource": "s1001"
        }
      ],
      "employees": [
        {
          "cui": "11054529",
          "name": "COMPANIA NATIONALA DE CAI FERATE CFR SA",
          "value": "24493",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "427410",
          "name": "COMPANIA NATIONALA POSTA ROMANA SA",
          "value": "20154",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1590120",
          "name": "REGIA NATIONALA A PADURILOR ROMSILVA RA",
          "value": "13625",
          "authority": "MINISTERUL MEDIULUI, APELOR SI PADURILOR",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "11054545",
          "name": "SOCIETATEA NATIONALA DE TRANSPORT FEROVIAR DE CALATORI - CFR - CALATORI SA",
          "value": "10597",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1589886",
          "name": "SOCIETATEA DE TRANSPORT BUCUREŞTI STB S.A.",
          "value": "9826",
          "authority": "CONSILIUL GENERAL AL MUNICIPIULUI BUCURESTI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "30267310",
          "name": "SOCIETATEA COMPLEXUL ENERGETIC OLTENIA S.A.",
          "value": "8565",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "16054368",
          "name": "COMPANIA NAŢIONALĂ DE ADMINISTRARE A INFRASTRUCTURII RUTIERE S.A.",
          "value": "6913",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "14056826",
          "name": "SOCIETATEA NATIONALA DE GAZE NATURALE  ROMGAZ  SA",
          "value": "5291",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13863739",
          "name": "METROREX SA",
          "value": "4882",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13068733",
          "name": "SOCIETATEA NAŢIONALĂ DE TRANSPORT GAZE NATURALE TRANSGAZ SA",
          "value": "3996",
          "authority": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13267213",
          "name": "SOCIETATEA DE PRODUCERE A ENERGIEI ELECTRICE IN HIDROCENTRALE  HIDROELECTRICA S.A.",
          "value": "3537",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "41269473",
          "name": "COMPANIA MUNICIPALĂ TERMOENERGETICA BUCUREŞTI S.A.",
          "value": "3409",
          "authority": "ASOCIATIA DE DEZVOLTARE INTRACOMUNITARA TERMOENERGETICA BUCURESTI-ILFOV",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "11054537",
          "name": "SOCIETATEA NATIONALA DE TRANSPORT FEROVIAR DE MARFA CFR - MARFA SA",
          "value": "3049",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1890420",
          "name": "RAJA SA",
          "value": "2391",
          "authority": "ASOCIATIA DE DEZVOLTARE INTERCOMUNITARA APA - CANAL CONSTANTA",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "12397185",
          "name": "COMPANIA NATIONALA LOTERIA ROMANA SA",
          "value": "2351",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "10874881",
          "name": "SOCIETATEA NATIONALA NUCLEARELECTRICA SA",
          "value": "2300",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "30859649",
          "name": "SOCIETATEA COMPLEXUL ENERGETIC VALEA JIULUI S.A.",
          "value": "2075",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "2351555",
          "name": "ADMINISTRATIA PATRIMONIULUI PROTOCOLULUI DE STAT RA",
          "value": "2056",
          "authority": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13328043",
          "name": "COMPANIA NATIONALA DE TRANSPORT AL ENERGIEI ELECTRICE TRANSELECTRICA SA",
          "value": "1976",
          "authority": "SECRETARIATUL GENERAL AL GUVERNULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "201217",
          "name": "COMPANIA DE APA SOMES SA",
          "value": "1922",
          "authority": "ASOCIATIA REGIONALA PENTRU DEZVOLTAREA INFRASTRUCTURII DIN BAZINUL HIDROGRAFIC SOMES-TISA",
          "authorityNameSource": "json_apt"
        }
      ],
      "loss": [
        {
          "cui": "11653560",
          "name": "COMPANIA NATIONALA UNIFARM SA",
          "value": "354232258",
          "authority": "MINISTERUL SANATATII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "10102377",
          "name": "C.E.T. GOVORA SA",
          "value": "275436396",
          "authority": "CONSILIUL JUDETEAN VALCEA",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "41269473",
          "name": "COMPANIA MUNICIPALĂ TERMOENERGETICA BUCUREŞTI S.A.",
          "value": "208204253",
          "authority": "ASOCIATIA DE DEZVOLTARE INTRACOMUNITARA TERMOENERGETICA BUCURESTI-ILFOV",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "30859649",
          "name": "SOCIETATEA COMPLEXUL ENERGETIC VALEA JIULUI S.A.",
          "value": "160415303",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "850",
          "name": "AVERSA SA",
          "value": "126613726",
          "authority": "AUTORITATEA PENTRU ADMINISTRAREA ACTIVELOR STATULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "2413593",
          "name": "SANTIERUL NAVAL 2 MAI SA",
          "value": "83612954",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1116683",
          "name": "NITRAMONIA SA",
          "value": "44867135",
          "authority": "AUTORITATEA PENTRU ADMINISTRAREA ACTIVELOR STATULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1576401",
          "name": "ROMAERO SA",
          "value": "39668659",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "13914972",
          "name": "UZINA DE AGENT TERMIC ŞI ALIMENTARE CU APĂ MOTRU SA",
          "value": "29669003",
          "authority": "CONSILIUL LOCAL MOTRU",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "31952982",
          "name": "TERMOFICARE ORADEA S.A.",
          "value": "28345790",
          "authority": "CONSILIUL LOCAL ORADEA",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "15811175",
          "name": "CET GRIVITA S.A.",
          "value": "27035688",
          "authority": "CONSILIUL LOCAL AL SECTORULUI BUCURESTI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "938970",
          "name": "REGIA AUTONOMA PENTRU PRODUCTIA DE TEHNICA MILITARA  UZINA AUTOMECANICA MORENI SUCURSALA",
          "value": "25087798",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "10254529",
          "name": "COMPANIA NATIONALA A URANIULUI SA",
          "value": "24791714",
          "authority": "MINISTERUL ENERGIEI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "14373832",
          "name": "SOCIETATEA UZINA MECANICĂ SADU SA FILIALA A COMPANIEI NAŢIONALE ROMARM   S.A.",
          "value": "24629383",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "1343872",
          "name": "REGIA AUTONOMĂ DE SERVICII PUBLICE PLOIEŞTI RA",
          "value": "22066878",
          "authority": "CONSILIUL LOCAL PLOIESTI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "8123890",
          "name": "ENET SA",
          "value": "19586904",
          "authority": "CONSILIUL LOCAL FOCSANI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "14639374",
          "name": "C.E.T. SA",
          "value": "14502737",
          "authority": "CONSILIUL LOCAL BACAU",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "11178217",
          "name": "SOCIETATEA NAŢIONALĂ AEROPORTUL INTERNAŢIONAL TIMIŞOARA-TRAIAN VUIA- SA",
          "value": "14384669",
          "authority": "MINISTERUL TRANSPORTURILOR SI INFRASTRUCTURII",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "16368506",
          "name": "COMPANIA NAŢIONALĂ ROMARM S.A. BUCUREŞTI FILIALA SOCIETATEA FABRICA DE ARME CUGIR S.A.",
          "value": "12799878",
          "authority": "MINISTERUL ECONOMIEI, DIGITALIZARII, ANTREPRENORIATULUI ŞI TURISMULUI",
          "authorityNameSource": "s1001"
        },
        {
          "cui": "14330840",
          "name": "ECONOMAT SECTOR 5 SRL",
          "value": "11578802",
          "authority": "CONSILIUL LOCAL AL SECTORULUI BUCURESTI",
          "authorityNameSource": "s1001"
        }
      ]
    }
  },
  "procurement": {
    "from": "2019-01",
    "to": "2026-12",
    "buyers": 778,
    "buyerDirect": 769,
    "buyerAwards": 488,
    "sellers": 822,
    "unknown": 0
  }
}
