import { DEFAULT_CAMPAIGN_ADMIN_PAGE_LIMIT } from "@/features/campaigns/buget/admin/constants";

/** Search payload for `/admin/campaigns/$campaignKey/entities/$entityCui` (users tab, default paging). */
export function createCampaignAdminEntityDetailRouteSearch() {
  return {
    tab: "users" as const,
    query: undefined,
    interactionId: undefined,
    hasPendingReviews: undefined,
    hasSubscribers: undefined,
    hasNotificationActivity: undefined,
    hasFailedNotifications: undefined,
    latestNotificationType: undefined,
    latestNotificationStatus: undefined,
    sortBy: undefined,
    sortOrder: undefined,
    cursor: undefined,
    pageIndex: undefined,
    limit: DEFAULT_CAMPAIGN_ADMIN_PAGE_LIMIT,
    configEntityCui: undefined,
    configUpdatedAtFrom: undefined,
    configUpdatedAtTo: undefined,
    configSortBy: undefined,
    configSortOrder: undefined,
    configCursor: undefined,
    configPageIndex: undefined,
    configLimit: undefined,
    selectedEntityCui: undefined,
    configCreate: undefined,
    threadsStateGroup: undefined,
    threadsThreadState: undefined,
    threadsResponseStatus: undefined,
    threadsQuery: undefined,
    threadsEntityCui: undefined,
    threadsUpdatedAtFrom: undefined,
    threadsUpdatedAtTo: undefined,
    threadsLatestResponseAtFrom: undefined,
    threadsLatestResponseAtTo: undefined,
    threadsSelectedThreadId: undefined,
    threadsCursor: undefined,
    threadsPageIndex: undefined,
    threadsLimit: undefined,
  };
}
