---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgC42wXnWUj67KAXnaiVc3FnfyvdBR3+xu2PNOHuwu7Igk2sbuEE9mIrgakA55e7mIPmF/HfpB6rYBh0IAZT3hg6v0d0hX0p/eXouU5wXquLOq2Y8oNGtVrwppPnihy7S54lHoJr/NLrIyU64PXRT31+y1s6+2NMi2TwWLWy7KScYF1tI3YMNo8OBKze59lBZO2t9Gg3nBtPdbJpLPAZTjxcNye5cxWf7Ty3Yye5/mr+GDbH9ScDWpkTZNlai+PgZ+WlckaSRGJE1XXgp6G1DkOJzvzXFfLvdu5JebusTgZqevOPwaYaPLmOV5dVOucv1HwSEo4jW5yOs37pcuQOye54xjLyy3dpBXRPCBoNDoVa53Ye8JD0vKc7ZjzkoJa+IxOmV0dgNgUkdu1zmkkEkFBf/OgqOs2stroLlkgqNSSzBj0PCcqXk9gEAR2mNlYIYkmFZ+Ee2Kweddzl3hl9ZACEu7MLEbCsyQBjIS6COuRRecMcSm+bG7xWf9GhJaygaN5G6NJs+v1cT9n/3pEpegcrosbQUlvIFIFEHoaDIzZiVbQXu8oo9SqLSGXZs6Ecr3wV/RXFFhho4xZF7bQlPIkA1ybcbqalabRruKUcmbKCm/8/+VbjUrPNtholG3SSVyn7w7FjXDf06jWQa5/Ix+8yadjETezdhrmiWHYmGEr2TXUwe8ebye94L+kCoC7gDfSWxQIuGI/2TKxsor8GQQpqNc4/bHh4ACUoxtfNdlyavN8JrKseG5DKZHqTjo3IQ60UwSDaGqLecNY/2a2gtzvFmu0gH2daehXrKO/Xv2SOhJ49cpVr+g042Py91l1PlvKfAYhwwVesPOooanFQqbmJDpIHD7dlVHqfdjvPU8U4fC6jnSraizH0wqld+sCNRVF7TMTB+/y/p1A2+DD3Pur9YBf+6mbAtO+OgQLiDosUqBHzwjBquEz3cg==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
