---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAcgvE8qNTugIc6sSyxWkBi/YQ3c9MsRKOTUM6vD2GdO26fXp3/pjTHqFNy7e72d7iArkPusiUOfL17HyoayzPd7D4hs+bFtVQ+pJ9I9QOGWkfAkuT9dyVx6hUa+8HYtKyRLVsvnh+iCT4DMcPynwbjVZo9JPaFfG9vvR6MI/h+/6Kl9YesSeIsA2SqLWLQCj5pGDoR0eLwwHJSFNYeeBVPLqzAOrsxpDSJEo/2KUZSMtRlP5rMWLD/ViC/YtZd+grSR68wNbO8w1wTaEgH2n2VuTFb5lEYsfzh7dCTBsKGkmRfZwyVpQMP61FHlbDJ+CTS9kcVvRHhITtsagLegEvmFSa2kABzNQ5w1aQsyxLSbR9qn8ifpk2OaNnmdDD1UPrsobgWnhwULxExyvHDM5AIzN/yggD7jIVD/wM2mKyAf1qqA+GgtQnSQuqyZyEkCoYuVWGbyKNqhD9JqdD2L/5wfLssTr5OjQDGRw1AXGQS8xoqb31O0DR97szSfEByYGzaSVGig6lLCgFdUcNlwqs0lxu+65IagsTqWpfiAn9CJpxDOfO+fQPuMt/UVJUjxGWhoacklsBobj36CXfToI/WVOoqKYnZC42At+8su7dyxqvvI4hEYDers6G/ZMLPHMXaZywVsB+VNyCfAaxj1Xou2qHOXsrcdfe2XGXpfEsTfKc26bVZDAE9lFx+HaJvIkJp5SlYyuKf47R8SS+aN4oPS8Hl6cpLeKIJZ75DzySsDpl7KMkKUuxDT+dwaIq2hsJHSKjCMqTmlWW3mezUziQuIEeIeRD0w/3IDSW4jekS6U1P0c4Hn/ErtdVS9b6csnlyRF5UNou+b/6y2fcpnKn5gFfNANDoEoQfM7fDLyKzEdIO2NRve+zEgg7py0N6HeVdq7eoyBxSrHAHeKQr16QcE+jg1GlzNri6EfkZfLExov0a/Yq/bfumXA==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
