apiVersion: v1
kind: ConfigMap
metadata:
  name: hack-for-facts-eb-client-config
  namespace: hack-for-facts
data:
  INTERNAL_API_URL: http://hack-for-facts-eb-server.transparenta-eu-dev.svc.cluster.local
  VITE_APP_ENVIRONMENT: development
  VITE_API_URL: https://dev-chronos-api.transparenta.eu
  VITE_API_USE_PROXY: "false"
  VITE_SITE_URL: https://dev-chronos.transparenta.eu
  VITE_POSTHOG_ENABLED: "false"
  VITE_SENTRY_ENABLED: "false"
  VITE_SENTRY_FEEDBACK_ENABLED: "false"
