---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAUhZHeWzZs6DexDwB2aXlmGwfl5404Aig+BPvTHOenYxtz2f0cxSt9YSZjYIIoD37Qo4RCq+rRL5UvOIqsCunSbfEEguvQGGfkT8klDXBNKmOD5WM9g2NRg+AMXx08a/MqWYlo0uL4p/KSb+3BIjEb6X7WPNHm7PWNeF0OQo/qSHoXW5XrSwcdL+P/NOKQf1JnGY4QAkEgJ6J24POeaF9zQ2JM8iRGq6X/9wFqcW2yRdj9XuxzXpFF3sDUVQM+yI5GsM5GbxTwY8dy4OKd/2DmuDoX8BVnNIIhs/A9lu6dymUTGvPdIJXtZ6jGV39v7wuTZyIoW/Whw66QRy+BlfKE0KmtdS1tktGupIt8xL0RUyhbSHNF1LVqVSXasEJudQ/kj19QS0Tj+C7ewZeKM9wR0iFOQS4T+svEA2MazHHpULb/Xk5/RHQ6xRrCWW/R8jzsnN6q0EWCR5wreErz5uUyorM673zLFGISy006dsLy4MgBh5sriyCjfGfFE4aL5QpfOk/kHz/CN1248kxnMfLfjxogUjFaY+raqrSnZG1I17zHcFQxQlSf+b5G9rNeIM0DGl7n6w+GQCegbMCV2dM6W5VQduT8OAf/5iZSmNT16WZNp4CyJ/mjEoh2/Fa6MhPNiGX9Uw5l+e0boMaFpCHCToBZB+PXCgqpmGKTxD6d2d4Tgq4+4IxxGZHBzZrA+WI4LcAmnud0/dlErM0xBDOgQlQRzamRwfwMYZeFzbHtvCYuswswKejbkbEjJgyrMqdEkFs2cc/tTYBpAeBk4TBQT2JQ8DY0xHLC+atwiuuQ4iMKA1y64T/u/24JIo3Q4wzLcoCpOcziRyWrHNO0JF0xpwS789jROlG0Jy4cTHUuTXMKSa8J7y/UCAibF8uw/N2E+k8b3qnpQ4qPxuyOUf7lgOEzc29IDSXLhVmg4IuuX0e/FNHseExhPQ==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
