---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCzDhBuCrGsPvAlGwtKpJi/i3uHpsYBcevLO2eJi8BgPKZNwbri2GkfMx8CmExoVbqUmnTls3R9g7bSLUwaqQo0S4kYuN1LQMi0mm+f8A4ddLFM79sPSqdn+8Wql3ucYvd7he852MhFBIUEC1zf3I5z+SFjWXZWpXYgWtb5Xu32+HAHLCXm6vt0kyvGwHAEhB6GcmNDF+r8h3Um/6b5VmJXTMCJS/C8m2JSMgkyniVPATBXGAAg4XMwvx3VVKd9wLhO8kO4eebLgTmHITipYjom9E7OaP7Oyb1RMVFgCfHXwZzfsrhGMPzAWFtoX6WbuKO1KKP6cOUeBoddpA2vLRseb8OGxgGT9WIHsDfslLfakLetBfhG+JmICPSammsjIIqKD3ZGf1JaJBrmunaz7tnBf3Sal0XW01/ux/ukRz+HAGiCyJkyE8GCMKY93mRKcafgv6ATHi0Bd4UdpcScvzxkh5wDZgiN19pBg4hZp509OrG8bMHcZQPIY430k2QgUb6I1s1dD4xn1dsjlKAfBXN++wmbo90AHfooLQPBtLfz74AK31T6tXdrRH1zSyBHoIzB1/t25z6rkok0BkRcl/GuWk9BAwOCkRfODp+vUi0Aq4aoVfu97OYuIhJuwGPt0jwaBbMXuYHEmb3uCaiYA398vc4AsY8dwYf7o12oJoKQx4pzrG+qopqTT02bFSSEQ/UVucmfhB3bNHD/67aMNjwvjLMM32uGnDHf/poYRix7uEzUFppsBy8lQMRtHu6q8gBrvmwgdXvE9iPLcMvalFD9Or3Sb90H7S2QgagOH3gDjdAmEzZqcdPCrKC93dhPOLkHtkEkdTqmcrBpoGvNwNhShjszxeECRHi1qP3FOsODXTN3dD02ylEt1lcyVyUEl3dBJWuiDV0SMcC70Ww/zl7trOTxeIqATPT7YzBtf4k+USLrQctnewotXw==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
