---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgClys66bvVrnVwvzjNJjfw66uvODuYBewBzAqK0LkhRgAX3ctYih89yYgjMPV0f+CInxeRossJlxOofa+c7lpO44ihIHQeTbaZ0/Fr+9oJcCEJbbal8oMZrVRfrYGlqxR2gvL4Tc0okspIEVfXze+d05VeRiU12dKeBr1pmik8jV/QNg71Nc1DhJJjrWQXeHtiwS7WpoRUtZCZpxV9ZUB3A0lrK1eq3eWxNTEk1MNir+jcjfgxgaWVGjaEoKqWGdU10uzb/T2ROS5qarDtDKc4iW2YUzEzpBv9V9g0OYUrfk/v+UH58tQ6V79NJ+91tEXjPdlegOPaqov4da1+Aq3Jid+TcoQ41vVg0qWAxiHg+nbob9FI3NaYKyeG2RCwe7L5n+1nhIhio9l2aCt267BvHWLqH+KAK9CTetlWLWU5C6m7lGWG6o+D2dKnEIOFdtlqxOIwfcHy8zKCYQ+rgVmIhxUmcnSzBTTJ8Es5rvdveiinhFqH7LoKaBJYPmCkqP7mIQYBFsUo5mR38sHiJ7DN6/Q+BiWTRs4SumgiysU8KqVErrgEO2RTVCOXOpSa7FhthyFjbW3YK3dXrNhslv21hzBtNOmzMZx2asncjG1m7Pa8jKSHUwTcjUJbVllHw26RDVB/0YXu8PwwxyKdkkB9JrR9kuEZEPnaeEH5SICDMec41myCjhFrhJ22NdAFCnTZWcreS8BSFxufRtsjowcmT8spCFmrUqz9RITEcTcho8azM7G3+ScI/Zvfmu7b+NXmDJMFtx+WmP6OSPimC3nxcoab9pwPLFDJYwZK9P2/sauMwnjOQ3ZVlBCT7sI3z30ZzVHmOE3MBOgMJ+Iy54DH5NOKgYTV3N6pOI5FH/s7EyTQy2ef8goNjFwzQPKoSi+Mi/paqaeaEtH1VViEJ5hq7gS+sAPEUxw4p/E44elBnrQQ/wmR+cbreYg==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
