/**
 * Build GraphQL filter-input objects from the UI's `ParliamentSearch` params.
 *
 * Each collection (votes/members/bills) has its own filter shape generated by
 * the server from the §7 specs. The functions here are pure: search params in,
 * filter object out, so they are unit-testable without a network. Empty/`all`
 * selections are dropped (omitted keys = no constraint), matching the companies
 * `buildCompaniesFilter` convention.
 */
import type {
  ParliamentBillsSearch,
  ParliamentMembersSearch,
  ParliamentVotesSearch,
} from '@/schemas/parliament'
import { VoteKindSchema } from '@/schemas/parliament'
import { toGraphqlChamber, toGraphqlVoteChamber } from './parliament-translate'

const VOTE_KIND_COUNT = VoteKindSchema.options.length

/** A vote-date bound in `YYYY-MM-DD` (the GraphQL `Date` scalar form). */
function toDateBound(value: string | undefined): string | undefined {
  const trimmed = value?.trim()
  if (!trimmed) return undefined
  // Accept full ISO timestamps from the date pickers; the server wants the day.
  const day = trimmed.slice(0, 10)
  return /^\d{4}-\d{2}-\d{2}$/.test(day) ? day : undefined
}

export interface ParliamentVotesFilterInput {
  chamber?: { eq: string }
  outcome?: { eq: string }
  voteDate?: { gte?: string; lte?: string }
  billKey?: { eq: string }
  q?: { contains: string }
  /**
   * Votes where ONE group's PLURALITY stance was `choice`.
   *
   * Plurality, not unanimity: a 91-member group splits, so the server picks the
   * choice with the most ballots on that vote. Two consequences the UI must
   * respect — a tie means the group took NO stance and the vote is excluded,
   * and the resulting COUNT OF VOTES is a different denominator from the
   * cohesion bar's share of BALLOT SLOTS. The two numbers will not agree and
   * must never be presented as if they do.
   */
  groupVote?: { group: string; choice?: string }
  kind?: { in: string[] }
}

/**
 * Votes filter. `chamber` maps the UI `camera|senat|comun` to the DB enum
 * (`comun` = joint sittings, a served value); `all` is dropped — the votes
 * connection is happy to run cross-chamber. `outcome` passes through
 * (`adoptat|respins` — the UI's `amânat` has no live rows and is simply never
 * sent). A `q` search is paired with whatever chamber/date bound is present
 * (the server's ILIKE fallback requires a bound; Meili-primary needs none).
 */
export function buildVotesFilter(
  search: ParliamentVotesSearch,
): ParliamentVotesFilterInput {
  const filter: ParliamentVotesFilterInput = {}

  if (search.chamber && search.chamber !== 'all') {
    filter.chamber = { eq: toGraphqlVoteChamber(search.chamber) }
  }
  if (search.outcome) {
    filter.outcome = { eq: search.outcome }
  }

  const gte = toDateBound(search.from)
  const lte = toDateBound(search.to)
  if (gte || lte) {
    filter.voteDate = { ...(gte ? { gte } : {}), ...(lte ? { lte } : {}) }
  }

  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  // The GROUP is what makes this a filter; the stance only narrows it further.
  // A group alone means "every vote this group cast ballots on"; a stance with
  // no group describes no subset at all, so it is dropped rather than sent.
  const group = search.grupVot?.trim()
  if (group) {
    filter.groupVote = {
      group,
      ...(search.alegere ? { choice: search.alegere } : {}),
    }
  }

  // A single value and an array both arrive as `tipVot`; normalise to the
  // server's `in` shape. Selecting EVERY kind is the same as selecting none, so
  // it is dropped rather than sent as a six-way `in` the planner must evaluate.
  const kinds = search.tipVot
    ? (Array.isArray(search.tipVot) ? search.tipVot : [search.tipVot])
    : []
  if (kinds.length > 0 && kinds.length < VOTE_KIND_COUNT) {
    filter.kind = { in: [...kinds] }
  }

  return filter
}

export interface ParliamentMembersFilterInput {
  legislature?: { eq: string }
  chamber?: { eq: string }
  group?: { in: string[] }
  judet?: { in: string[] }
  q?: { contains: string }
  /**
   * Current-seat filter (SC-1). Set ONLY for composition/roster/seat-count
   * surfaces — NEVER for attribution/career/voting-history/member-detail/
   * bill-initiators (those keep all mandate rows). Not added by
   * `buildMembersFilter` (the directory shows all mandates); the hub/roster
   * paths add it explicitly.
   */
  current?: { eq: boolean }
}

/**
 * Members filter. `legislature` is always present (bounds the scan) and is
 * supplied by the live module (default = latest). `group`/`judet` are the
 * RESOLVED display values (group_name / constituency_name) — the live module
 * resolves slugs via `parliamentResolveFilter` before calling this. The chamber
 * `all` selection is dropped (members span both chambers), and so is `comun` —
 * it is a VOTES-tab value on the shared search object, and no member roster
 * belongs to a joint sitting.
 */
export function buildMembersFilter(
  search: ParliamentMembersSearch,
  resolved: {
    legislature: string
    groupNames?: string[]
    constituencyNames?: string[]
  },
): ParliamentMembersFilterInput {
  const filter: ParliamentMembersFilterInput = {
    legislature: { eq: resolved.legislature },
  }

  if (search.chamber && search.chamber !== 'all' && search.chamber !== 'comun') {
    filter.chamber = { eq: toGraphqlChamber(search.chamber) }
  }
  if (resolved.groupNames && resolved.groupNames.length > 0) {
    filter.group = { in: resolved.groupNames }
  }
  if (resolved.constituencyNames && resolved.constituencyNames.length > 0) {
    filter.judet = { in: resolved.constituencyNames }
  }
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  return filter
}

/** Server bill-type tokens (ParliamentBillsFilter.billType). */
export type ServerBillType = 'government' | 'parliamentary'
/** Server bill-status tokens (ParliamentBillsFilter.status, bill-lifecycle.v2). */
export type ServerBillStatus =
  | 'promulgated'
  | 'rejected'
  | 'withdrawn'
  | 'lapsed'
  | 'in_progress'

export interface ParliamentBillsFilterInput {
  year?: { eq: number }
  finalized?: { isNull: boolean }
  q?: { contains: string }
  billType?: { eq: ServerBillType }
  status?: { eq: ServerBillStatus }
}

export type ParliamentBillSortInput =
  | 'updated_desc'
  | 'updated_asc'
  | 'title_asc'
  | 'title_desc'

/**
 * UI billType enum → server token. The server has only government/parliamentary
 * (initiative source); citizen initiatives are non-government → parliamentary,
 * and ordinance-approval projects are government acts → government. Returns
 * undefined for anything unmapped so we never send a raw/unknown token.
 */
const BILL_TYPE_TO_SERVER: Readonly<Record<string, ServerBillType>> = {
  guvern: 'government',
  ordonanta: 'government',
  parlamentar: 'parliamentary',
  cetateni: 'parliamentary',
}

/**
 * UI billLocation enum → server status token (bill-lifecycle.v2 five-bucket
 * partition). Terminal outcomes map 1:1 (promulgat→promulgated,
 * respins→rejected, retras→withdrawn, clasat→lapsed); the in-pipeline
 * locations (camera/senat/mediere/presedinte) → in_progress.
 */
const BILL_LOCATION_TO_STATUS: Readonly<Record<string, ServerBillStatus>> = {
  promulgat: 'promulgated',
  respins: 'rejected',
  retras: 'withdrawn',
  clasat: 'lapsed',
  camera: 'in_progress',
  senat: 'in_progress',
  mediere: 'in_progress',
  presedinte: 'in_progress',
}

/**
 * Bills filter — now fully SERVER-backed (billType + status columns landed on
 * :3001). billType/billLocation are mapped to the server's quoted tokens and
 * AND-composed with q/year/finalized; filtering spans the FULL result set, so
 * pagination is honest (no client-side over-page facet). Only the allowed tokens
 * are ever sent (unmapped UI values are dropped, never forwarded raw).
 */
export function buildBillsFilter(
  search: ParliamentBillsSearch,
): ParliamentBillsFilterInput {
  const filter: ParliamentBillsFilterInput = {}
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  if (search.billType) {
    const token = BILL_TYPE_TO_SERVER[search.billType]
    if (token) filter.billType = { eq: token }
  }
  if (search.billLocation) {
    const token = BILL_LOCATION_TO_STATUS[search.billLocation]
    if (token) filter.status = { eq: token }
  }
  return filter
}

export function buildBillsSort(
  search: ParliamentBillsSearch,
): ParliamentBillSortInput {
  switch (search.sortBy) {
    case 'title_asc':
    case 'title_desc':
    case 'updated_asc':
      return search.sortBy
    case 'updated_desc':
    default:
      return 'updated_desc'
  }
}

