/**
 * Build GraphQL filter-input objects from the UI's `ParliamentSearch` params.
 *
 * Each collection (votes/members/bills) has its own filter shape generated by
 * the server from the §7 specs. The functions here are pure: search params in,
 * filter object out, so they are unit-testable without a network. Empty/`all`
 * selections are dropped (omitted keys = no constraint), matching the companies
 * `buildCompaniesFilter` convention.
 */
import type {
  ParliamentBillsSearch,
  ParliamentMembersSearch,
  ParliamentVotesSearch,
} from '@/schemas/parliament'
import { toGraphqlChamber } from './parliament-translate'

/** A vote-date bound in `YYYY-MM-DD` (the GraphQL `Date` scalar form). */
function toDateBound(value: string | undefined): string | undefined {
  const trimmed = value?.trim()
  if (!trimmed) return undefined
  // Accept full ISO timestamps from the date pickers; the server wants the day.
  const day = trimmed.slice(0, 10)
  return /^\d{4}-\d{2}-\d{2}$/.test(day) ? day : undefined
}

export interface ParliamentVotesFilterInput {
  chamber?: { eq: string }
  outcome?: { eq: string }
  voteDate?: { gte?: string; lte?: string }
  billKey?: { eq: string }
  q?: { contains: string }
}

/**
 * Votes filter. `chamber` maps the UI `camera|senat` to the DB enum; `all` is
 * dropped. `outcome` passes through (`adoptat|respins` — the UI's `amânat` has
 * no live rows and is simply never sent). A `q` search is paired with whatever
 * chamber/date bound is present (the server's ILIKE fallback requires a bound;
 * if the caller gives none we still send `q` and let the server reject — the
 * live module guards this by defaulting the chamber upstream).
 */
export function buildVotesFilter(
  search: ParliamentVotesSearch,
): ParliamentVotesFilterInput {
  const filter: ParliamentVotesFilterInput = {}

  if (search.chamber && search.chamber !== 'all') {
    filter.chamber = { eq: toGraphqlChamber(search.chamber) }
  }
  if (search.outcome && search.outcome !== 'amânat') {
    filter.outcome = { eq: search.outcome }
  }

  const gte = toDateBound(search.from)
  const lte = toDateBound(search.to)
  if (gte || lte) {
    filter.voteDate = { ...(gte ? { gte } : {}), ...(lte ? { lte } : {}) }
  }

  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  return filter
}

export interface ParliamentMembersFilterInput {
  legislature?: { eq: string }
  chamber?: { eq: string }
  group?: { in: string[] }
  judet?: { in: string[] }
  q?: { contains: string }
  /**
   * Current-seat filter (SC-1). Set ONLY for composition/roster/seat-count
   * surfaces — NEVER for attribution/career/voting-history/member-detail/
   * bill-initiators (those keep all mandate rows). Not added by
   * `buildMembersFilter` (the directory shows all mandates); the hub/roster
   * paths add it explicitly.
   */
  current?: { eq: boolean }
}

/**
 * Members filter. `legislature` is always present (bounds the scan) and is
 * supplied by the live module (default = latest). `group`/`judet` are the
 * RESOLVED display values (group_name / constituency_name) — the live module
 * resolves slugs via `parliamentResolveFilter` before calling this. The chamber
 * `all` selection is dropped (members span both chambers).
 */
export function buildMembersFilter(
  search: ParliamentMembersSearch,
  resolved: {
    legislature: string
    groupNames?: string[]
    constituencyNames?: string[]
  },
): ParliamentMembersFilterInput {
  const filter: ParliamentMembersFilterInput = {
    legislature: { eq: resolved.legislature },
  }

  if (search.chamber && search.chamber !== 'all') {
    filter.chamber = { eq: toGraphqlChamber(search.chamber) }
  }
  if (resolved.groupNames && resolved.groupNames.length > 0) {
    filter.group = { in: resolved.groupNames }
  }
  if (resolved.constituencyNames && resolved.constituencyNames.length > 0) {
    filter.judet = { in: resolved.constituencyNames }
  }
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  return filter
}

/** Server bill-type tokens (ParliamentBillsFilter.billType). */
export type ServerBillType = 'government' | 'parliamentary'
/** Server bill-status tokens (ParliamentBillsFilter.status). */
export type ServerBillStatus = 'promulgated' | 'rejected' | 'in_progress'

export interface ParliamentBillsFilterInput {
  year?: { eq: number }
  finalized?: { isNull: boolean }
  q?: { contains: string }
  billType?: { eq: ServerBillType }
  status?: { eq: ServerBillStatus }
}

export type ParliamentBillSortInput =
  | 'updated_desc'
  | 'updated_asc'
  | 'title_asc'
  | 'title_desc'

/**
 * UI billType enum → server token. The server has only government/parliamentary
 * (initiative source); citizen initiatives are non-government → parliamentary,
 * and ordinance-approval projects are government acts → government. Returns
 * undefined for anything unmapped so we never send a raw/unknown token.
 */
const BILL_TYPE_TO_SERVER: Readonly<Record<string, ServerBillType>> = {
  guvern: 'government',
  ordonanta: 'government',
  parlamentar: 'parliamentary',
  cetateni: 'parliamentary',
}

/**
 * UI billLocation enum → server status token. promulgat→promulgated,
 * respins→rejected; the in-pipeline locations (camera/senat/mediere/presedinte)
 * → in_progress. `retras` (withdrawn) has no server token → no filter (better
 * than mislabelling it rejected).
 */
const BILL_LOCATION_TO_STATUS: Readonly<Record<string, ServerBillStatus>> = {
  promulgat: 'promulgated',
  respins: 'rejected',
  camera: 'in_progress',
  senat: 'in_progress',
  mediere: 'in_progress',
  presedinte: 'in_progress',
}

/**
 * Bills filter — now fully SERVER-backed (billType + status columns landed on
 * :3001). billType/billLocation are mapped to the server's quoted tokens and
 * AND-composed with q/year/finalized; filtering spans the FULL result set, so
 * pagination is honest (no client-side over-page facet). Only the allowed tokens
 * are ever sent (unmapped UI values are dropped, never forwarded raw).
 */
export function buildBillsFilter(
  search: ParliamentBillsSearch,
): ParliamentBillsFilterInput {
  const filter: ParliamentBillsFilterInput = {}
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  if (search.billType) {
    const token = BILL_TYPE_TO_SERVER[search.billType]
    if (token) filter.billType = { eq: token }
  }
  if (search.billLocation) {
    const token = BILL_LOCATION_TO_STATUS[search.billLocation]
    if (token) filter.status = { eq: token }
  }
  return filter
}

export function buildBillsSort(
  search: ParliamentBillsSearch,
): ParliamentBillSortInput {
  switch (search.sortBy) {
    case 'title_asc':
    case 'title_desc':
    case 'updated_asc':
      return search.sortBy
    case 'updated_desc':
    default:
      return 'updated_desc'
  }
}

