/**
 * Build GraphQL filter-input objects from the UI's `ParliamentSearch` params.
 *
 * Each collection (votes/members/bills) has its own filter shape generated by
 * the server from the §7 specs. The functions here are pure: search params in,
 * filter object out, so they are unit-testable without a network. Empty/`all`
 * selections are dropped (omitted keys = no constraint), matching the companies
 * `buildCompaniesFilter` convention.
 */
import type {
  BillType,
  ParliamentBillsSearch,
  ParliamentMembersSearch,
  ParliamentVotesSearch,
} from '@/schemas/parliament'
import { toGraphqlChamber } from './parliament-translate'

/** A vote-date bound in `YYYY-MM-DD` (the GraphQL `Date` scalar form). */
function toDateBound(value: string | undefined): string | undefined {
  const trimmed = value?.trim()
  if (!trimmed) return undefined
  // Accept full ISO timestamps from the date pickers; the server wants the day.
  const day = trimmed.slice(0, 10)
  return /^\d{4}-\d{2}-\d{2}$/.test(day) ? day : undefined
}

export interface ParliamentVotesFilterInput {
  chamber?: { eq: string }
  outcome?: { eq: string }
  voteDate?: { gte?: string; lte?: string }
  billKey?: { eq: string }
  q?: { contains: string }
}

/**
 * Votes filter. `chamber` maps the UI `camera|senat` to the DB enum; `all` is
 * dropped. `outcome` passes through (`adoptat|respins` — the UI's `amânat` has
 * no live rows and is simply never sent). A `q` search is paired with whatever
 * chamber/date bound is present (the server's ILIKE fallback requires a bound;
 * if the caller gives none we still send `q` and let the server reject — the
 * live module guards this by defaulting the chamber upstream).
 */
export function buildVotesFilter(
  search: ParliamentVotesSearch,
): ParliamentVotesFilterInput {
  const filter: ParliamentVotesFilterInput = {}

  if (search.chamber && search.chamber !== 'all') {
    filter.chamber = { eq: toGraphqlChamber(search.chamber) }
  }
  if (search.outcome && search.outcome !== 'amânat') {
    filter.outcome = { eq: search.outcome }
  }

  const gte = toDateBound(search.from)
  const lte = toDateBound(search.to)
  if (gte || lte) {
    filter.voteDate = { ...(gte ? { gte } : {}), ...(lte ? { lte } : {}) }
  }

  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  return filter
}

export interface ParliamentMembersFilterInput {
  legislature?: { eq: string }
  chamber?: { eq: string }
  group?: { in: string[] }
  judet?: { in: string[] }
  q?: { contains: string }
}

/**
 * Members filter. `legislature` is always present (bounds the scan) and is
 * supplied by the live module (default = latest). `group`/`judet` are the
 * RESOLVED display values (group_name / constituency_name) — the live module
 * resolves slugs via `parliamentResolveFilter` before calling this. The chamber
 * `all` selection is dropped (members span both chambers).
 */
export function buildMembersFilter(
  search: ParliamentMembersSearch,
  resolved: {
    legislature: string
    groupNames?: string[]
    constituencyNames?: string[]
  },
): ParliamentMembersFilterInput {
  const filter: ParliamentMembersFilterInput = {
    legislature: { eq: resolved.legislature },
  }

  if (search.chamber && search.chamber !== 'all') {
    filter.chamber = { eq: toGraphqlChamber(search.chamber) }
  }
  if (resolved.groupNames && resolved.groupNames.length > 0) {
    filter.group = { in: resolved.groupNames }
  }
  if (resolved.constituencyNames && resolved.constituencyNames.length > 0) {
    filter.judet = { in: resolved.constituencyNames }
  }
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }

  return filter
}

export interface ParliamentBillsFilterInput {
  year?: { eq: number }
  finalized?: { isNull: boolean }
  q?: { contains: string }
}

export type ParliamentBillSortInput =
  | 'updated_desc'
  | 'updated_asc'
  | 'title_asc'
  | 'title_desc'

/**
 * Bills filter. The UI bill `billType` / `billLocation` filters have NO live
 * backing column (they are derived client-side from title + events — see the
 * mapper), so they are intentionally NOT translated to filter args here and are
 * reported as a server gap. Only `q` (title/number) and the implicit "became
 * law" facet have live columns. `billLocation: 'promulgat'` is mapped to the
 * `finalized` facet (final_law_number IS NOT NULL) as a best-effort.
 */
export function buildBillsFilter(
  search: ParliamentBillsSearch,
): ParliamentBillsFilterInput {
  const filter: ParliamentBillsFilterInput = {}
  const q = search.q?.trim()
  if (q) filter.q = { contains: q }
  if (search.billLocation === 'promulgat') {
    filter.finalized = { isNull: false }
  }
  return filter
}

export function buildBillsSort(
  search: ParliamentBillsSearch,
): ParliamentBillSortInput {
  switch (search.sortBy) {
    case 'title_asc':
    case 'title_desc':
    case 'updated_asc':
      return search.sortBy
    case 'updated_desc':
    default:
      return 'updated_desc'
  }
}

/** UI bill types that have a live filter column. None do today (gap). */
export const BILL_TYPES_WITHOUT_LIVE_FILTER: readonly BillType[] = [
  'guvern',
  'parlamentar',
  'cetateni',
  'ordonanta',
]
