---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    .dockerconfigjson: AgBGQbAEELPlj9i1U5F9ZF/CJNQtmA4/UQy7o5elV64i9wdlQpBTsv9+xjpjV8lrAzENvDHZyAZ7lL/BxM/32ZtDp4zJIRsMubngFx6h3CScwU7qiscN0fbOIHUC3ROwFMJNgiFXtxDFok15JWvaN5XC2oWguKLVHlaPIQlK9OTZg3C2kCzqnKsm4e9d9ii8ZYboW1jyYR4H+0tGmM7Kf62MG29+Y6g/DjRrTjCsuKuYvhr2+bTC1Gjs5PyF1r0bpyuAhvVSCwQ7Xn4riM95aKwOM+S2Qvr7ogh4XuvxhKz1/NkHwuNraAot7C6e06vAvs259zfGNtE/cKHSMfEF2Be5vw5Or4+h8ipnxTBDgE/nmVEQH+cxrQU7P75FLMPsYnTVyo4T8eeTVU/SDHDMCPwGxwXZ4ZHe8pP0B26oBdJewFwluwVeM3X71//0vFHBiaNKqZIQ9Jg6Nz7aq50e0Qa64niclwEPndxewPSu+LfjZUThS1wh/DKRgIp0L1LmtC0fTY3AX4QAar05wdoYtkr2ecBGt3kNcoBIHP9+Rw6Ny0QJ/oHEs7eNRQ72YAkqzMXet3JBeWlb9sTq40bUgMDeOA40vZvcc2/cbabq9gpNcvKSmn9+bblkqg2THHu829AkufvLafh7hTECgz5pEuAh9095wVehNgEpfUQWlMMdVjUQJh7XuGOmAhGfQKsOJwJ4A3q4m8+Ia/NWOthJQJ9KFzxsZJRtUBPGrtdKXPLocNftdddpkpWgdfyqtLXsqq94e6D4GibMF+5yPqCLrTZpGZPa6bxHO28Z/MuhRxyU75recgIupWDhGsdp4U3OPRt9LpiXmStuiCX/X1FtsTVXCHfs8V9+L/eb8Rgbl3leMgv7PD3emubwy7hwivrTbG1S+VVg6b6JZj3rqGKUtfs1lDs2+ouFHeWHtnVkL1YKrpStkcvt5Qf0h/zI8nPOmV39NzF3ldbQxI6vwQAPII3e65RDyImGlMT8QsZPrevVO55rANP85AWqGhlqtbJxvoVyzVlVgIZ25Q==
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/part-of: transparenta-eu
      name: registry-credentials-client
      namespace: transparenta-eu-dev
    type: kubernetes.io/dockerconfigjson
