---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    .dockerconfigjson: AgA+BPD9OtLh2gjo3BrVxWTSyETTkFRJ6/UQ4reDsqYhfFhGypdPsy0+x+0Ru6Cg2PLr/T0tVjV2C2S7KDfaITgb3mEebiXvHIIifLKXdIuPqfLENsYGJkOyJd6Szr6ZPmK31/bH53A/+0U9UvJOMFwAT3gFl1VKq7K/G5/0JKCVhWO/JZkOgjVwFbUily5/2sKUEjHI6U0bPpIhP5/KQaNeiiTJE6YxQuvcyZXdmPjD3PhA6ueqVfhPWvPCpUMWXOcggxkBj5+kv10zKIo0Hb9I1JMOjOgsxy7jvMNmkPxY2re2thNJ4BrbIkxPPrWAWIemf7OJdmW0j1PzJouaThVqVnjuKdSVL3Lp9fHmcFcrS7E2/hVs9c7X6YooyLxQ2uJnooodNABGYvvQF+m+7dMOAmvxry1yeqZsLvw/tNaz1JgNE5b3FWvqttHnJ5c+xm5vOsVmhFSkoihUlbiQKYGzPh1gZr3n94Hj00PfI4rp7S8ZAsO8pQMs0OtHIa519q+ZsR1wWfF2FpgmxchoSalxCcn7YsF41CP3j8/gsAiUL1XipAW3P2gNDlraO6eCdkO5vitrqoAoFL+5h3tSXDA6t8284/qvk+snWkAJMoMgqCMO7Hhi+zxIh5rNJCC8Co9tZ8ENDzPw6Bbeqe2OenO7S+oQuLMBtBKdVYu79cQavrNrZXaCFVaip2h6WJDqec2+x2Spd1iqSzQcgraJLYNCqJj1A1LcDCllcha45NSq96Pua8uM89c8jAW6Jkl0Gmn+xkP+iv7Ms3NTmVE0jp3c0OxC1hXsdvs0yn73P1L9dxLNaSM2vB21Im+Sj3MjAvZMbSdSkJF6M6VJ+PgvmeYlpqgmfh+xbmmG6bCglW84jIDTBVG5r4xmkpZVmMQ6WuyZoV5rRJ89dRnS3IMiGegNkSAmYYGdt05ioXVATH7enUH2CQpyuvslr38OV+H1EPFKqwASs3bMV0vUdUH9G4/04nMw/yygQwXSLM5uNIl20y2iV/dYjN2avN2fdFL9M7OXfetZirZthw==
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/part-of: transparenta-eu
      name: registry-credentials-client
      namespace: transparenta-eu-dev
    type: kubernetes.io/dockerconfigjson
