import type { PrototypeDefinition } from '@/development/harness/entry'
import { EchrByYear, EchrFlow } from './cedo.page'

/**
 * The European Court of Human Rights' judgments in cases against Romania
 * (justice-portal, 7 October 2026), from a snapshot of the judicial API's
 * HUDOC rows (`src/features/justice/lib/echr-snapshot.ts`, regenerated by
 * `scripts/generate-justice-echr-snapshot.mjs`). The head with the year, four
 * figures, the year's judgments with their applications and links to HUDOC,
 * one source line. The variants differ in how the years are drawn.
 * The owner picked `flux` as two tabs, promoted to `/justice/echr`. Decisions and
 * data rules: `docs/design/justice/design.md` §17–18.
 */
export const prototype = {
  title: 'Justiție — CEDO',
  spec: 'docs/design/justice/design.md',
  variants: {
    ani: {
      title: 'Ani — hotărârile anului, apoi anii ca bare',
      component: EchrByYear,
      note: 'The analysis page’s order: the year’s judgments first, then the judgments of every year as columns; a column takes its year.',
    },
    flux: {
      title: 'Flux — două taburi: anii (comunicate, decizii, hotărâri) și hotărârile anului',
      component: EchrFlow,
      note: 'The answer under two tabs, as the analysis page’s groupings: the years as rows of what reached the Court’s steps (communicated, decided, judged, applications, wait), a row opening its judgments; and the chosen year’s judgments. The tab is in the address (vedere).',
    },
  },
  compare: ['ani', 'flux'],
} satisfies PrototypeDefinition
