import type { PrototypeDefinition } from '@/development/harness/entry'
import { HubDrum, HubMaterii, HubRegistru } from './hub.variants'

/**
 * The court portal's front door (justice-portal, 7 October 2026), on the live
 * judicial API's figures (`hub.data.json`, regenerated by
 * `scripts/generate-justice-hub-fixtures.mjs`). Three variants in the
 * procurement, INS and companies hubs' language; they share the bands and
 * differ in the hero's panel and the bands' order. Decisions and data rules:
 * `docs/design/justice/design.md` §12–13.
 */
export const prototype = {
  title: 'Justiție — prima pagină',
  spec: 'docs/design/justice/design.md',
  variants: {
    registru: {
      title: 'Registru — cele mai încărcate instanțe lângă titlu, harta întâi',
      component: HubRegistru,
      note: 'The procurement front door shape: the busiest courts of the year by level beside the headline; then counties, matters, levels, courts, years, other courts.',
    },
    drum: {
      title: 'Drum — drumul unui dosar pe trepte lângă titlu',
      component: HubDrum,
      note: 'A case’s way up the court levels, with the stage counts, beside the headline; matters first, the map later.',
    },
    materii: {
      title: 'Materii — 100 de dosare pe materii lângă titlu',
      component: HubMaterii,
      note: 'The most graphical door: a hundred of the year’s cases by matter beside the headline; matters first, then the map.',
    },
  },
  compare: ['registru', 'drum', 'materii'],
} satisfies PrototypeDefinition
