/**
 * The ECHR snapshot's years, read on 2026-10-08.
 *
 * Generated by `scripts/generate-justice-echr-snapshot.mjs` beside `echr-snapshot.ts`, so a route can know them without
 * loading the snapshot; never edit by hand.
 */

/** The first and the last year the snapshot holds a document in; every year between holds one. */
export const ECHR_FIRST_YEAR = 2009
export const ECHR_LAST_YEAR = 2026
/** The last year the capture holds whole (the one before its newest document's): the page describes it by default. */
export const ECHR_REFERENCE_YEAR = 2025
