/**
 * The court portal capture's years, from the front door's snapshot read on 2026-10-07.
 *
 * Generated by `scripts/generate-justice-hub-snapshot.mjs` beside `hub-snapshot.ts`, so a route can know them without
 * loading the snapshot; never edit by hand.
 */

/** The last calendar year the capture covers whole: the pages describe it by default. */
export const JUSTICE_REFERENCE_YEAR = 2025
/** The first year the capture holds whole; the years before hold only cases still active later. */
export const JUSTICE_FIRST_WHOLE_YEAR = 2023
/** The year the capture stops in: a part-year. */
export const JUSTICE_LAST_CAPTURE_YEAR = 2026
