/**
 * The shape of the NGO finances summary kept in the client
 * (`finance-summary.ts`, generated by `scripts/summarize-ngo-finances.mjs`).
 *
 * The figures are the annual financial statements non-profit legal persons
 * file with the Ministry of Finance, published on data.gov.ro one file per
 * year. They include every non-profit that files: associations and
 * foundations, and also unions, religious bodies, political parties and
 * mutual-aid funds, each under its own activity. Money is in whole lei, as
 * reported, never adjusted for inflation.
 */

/**
 * The reader's domains, from the non-profit activity (CAEN) each statement
 * declares. `general` is the catch-all code 9499 („other membership
 * organisations"), which says nothing about the domain; `other` is every
 * code no domain claims.
 */
export type NgoFinanceDomainKey =
  | 'sport'
  | 'social'
  | 'education'
  | 'health'
  | 'culture'
  | 'religion'
  | 'professional'
  | 'unions'
  | 'finance'
  | 'agriculture'
  | 'political'
  | 'other'
  | 'general'

/**
 * Classes of total revenue in the year, in lei; `negative` holds the few
 * statements that report reversals as revenue below zero, `unknown` those
 * whose total revenue cell is blank (unknown, never zero: not in `none`).
 */
export type NgoFinanceSizeKey = 'negative' | 'none' | 'under10k' | 'under100k' | 'under1m' | 'over1m' | 'unknown'

export interface NgoFinanceDomain {
  readonly key: NgoFinanceDomainKey
  readonly statements: number
  /** Total revenue, lei. */
  readonly revenue: number
}

export interface NgoFinanceSize {
  readonly key: NgoFinanceSizeKey
  readonly statements: number
  readonly revenue: number
}

export interface NgoFinanceYear {
  readonly year: number
  readonly statements: number
  /** Total revenue of the year's statements, lei, the excluded ones apart. */
  readonly revenue: number
  /** When data.gov.ro last changed the year's file, `YYYY-MM-DD`. */
  readonly published: string
  /**
   * The year's first publication, without the late filers its revision adds
   * about a year later (2023's revision added 7% of statements, 4% of revenue).
   */
  readonly firstRelease: boolean
}

/**
 * One of the year's largest by revenue among the organisations the NGO
 * profile resolves — registry entries whose CUI the platform admitted, by the
 * registry's declaration or an exact name and county match at ANAF.
 */
export interface NgoFinanceLeader {
  readonly cui: string
  /** The registry's name for the organisation. */
  readonly name: string
  /** County code, or null where the registry has none. */
  readonly county: string | null
  readonly domain: NgoFinanceDomainKey
  readonly revenue: number
  /** Revenue the year before, or null when there was no statement that year. */
  readonly previous: number | null
  /** The registry status now, when it is not „Înregistrat". */
  readonly status: 'dissolved' | 'inLiquidation' | 'deregistered' | null
}

/** A statement left out of every sum by the hub's rule (a revenue above 1 bn lei): a value to verify, never a proven error. */
export interface NgoFinanceExcluded {
  readonly year: number
  readonly cui: string
  /** The total revenue reported, lei. */
  readonly revenue: number
  /** The revenue is exactly the statement's fixed assets (I1): a reason to verify it, which alone excludes nothing. */
  readonly equalsFixedAssets: boolean
  /** The organisation has an NGO profile, where the statement can be read. */
  readonly profile: boolean
}

export interface NgoFinanceSummary {
  /** The latest year with published statements. */
  readonly year: number
  /** The file the year's figures come from, and when data.gov.ro last changed it (`YYYY-MM-DD`). */
  readonly source: { readonly dataset: string; readonly file: string; readonly published: string }
  readonly statements: number
  /** Statements that report any revenue. */
  readonly withRevenue: number
  readonly revenue: number
  /** Revenue by where it came from; the three add up to `revenue`. */
  readonly sources: { readonly nonProfit: number; readonly economic: number; readonly special: number }
  readonly sizes: readonly NgoFinanceSize[]
  readonly domains: readonly NgoFinanceDomain[]
  /** Every year with a published file, oldest first. */
  readonly years: readonly NgoFinanceYear[]
  /** Statements left out of every sum, whole, by the hub's rule: a revenue above 1 bn lei, to verify. */
  readonly excluded: readonly NgoFinanceExcluded[]
  readonly leaders: readonly NgoFinanceLeader[]
}
