/**
 * The shape of the NGO registry's summary kept in the client
 * (`registry-summary.ts`, generated by `scripts/summarize-ngo-registry.mjs`).
 *
 * Every count is of registry entries. The registry is the Ministry of
 * Justice's export; an entry is an organisation as the registry records it,
 * and only rows repeated field for field are dropped, so a count is never
 * sharper than the registry itself.
 */

export type NgoRegistryStatusKey = 'registered' | 'deregistered' | 'inLiquidation' | 'dissolved'

export type NgoRegistryCategoryKey = 'association' | 'foundation' | 'federation' | 'religious_association' | 'foreign_legal_person'

export interface NgoRegistryCountySummary {
  /** The county code the map and the INS pages use (`CJ`, `B`). */
  readonly code: string
  /** The county as the registry spells it — the registry filter matches it exactly. */
  readonly source: string
  /** Entries with the status „Înregistrat". */
  readonly registered: number
  /** New entries in the summary's `year` — registry numbers given that year — whatever their status now. */
  readonly added: number
  /** Resident population on 1 January of the summary's `year` (INS POP105A). */
  readonly residents: number
}

export interface NgoRegistrySummary {
  readonly snapshotId: string
  readonly sourceUrl: string
  /** When the registry export was captured, `YYYY-MM-DD`. */
  readonly capturedAt: string
  /** The latest registration date in the export: how far it reaches. */
  readonly lastRegistration: string
  /** Rows in the export, repeated rows included. */
  readonly entries: number
  /** Rows dropped because another row repeats them field for field. */
  readonly repeated: number
  readonly status: Readonly<Record<NgoRegistryStatusKey, number>>
  /** Registered entries by legal form. */
  readonly categories: Readonly<Record<NgoRegistryCategoryKey, number>>
  /** Registered entries the registry marks as being of public utility. */
  readonly publicUtility: number
  /** Registered entries with no county, or an undetermined one. */
  readonly noCounty: number
  /** The last full year of new entries and the population year. */
  readonly year: number
  /**
   * New entries per year from 2001 to `year`, by the year in the registry
   * number (`3446/A/2026`), whatever the entry's status now. Not by the
   * registration date: that date moves when an entry changes, the number does not.
   */
  readonly registrations: readonly { readonly year: number; readonly count: number }[]
  readonly counties: readonly NgoRegistryCountySummary[]
}
