import type { ScraperDatasetReference } from './types'

const experimental = (path: string) => `experimental/docs/${path}`
const newLatest = (path: string) => `new_latest/${path}`

export const scraperDatasetCatalog: readonly ScraperDatasetReference[] = [
  {
    id: 'reference-codes',
    title: 'Reference codes (SIRUTA, CAEN, CPV, ANCPI)',
    description:
      'Shared join spine for geography, activity, and procurement classification.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA', 'CAEN', 'CPV', 'NUTS'],
    scrapperRepoRelativePath: experimental('reference-code-contracts.md'),
    experimentalDocs: [
      experimental('reference-code-contracts.md'),
      experimental('join-key-matrix.md'),
      experimental('geo-reference.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: ['src/lib/api/map-series.ts', 'src/components/maps/'],
    clientSchemaPaths: ['src/schemas/entities.ts', 'src/schemas/map-filters.ts'],
    clientSpecPaths: [],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'budget-execution',
    title: 'Budget execution (ANAF extranet)',
    description: 'Core public budget income/expense data for entities and UATs.',
    lifecycle: 'production',
    joinKeys: ['entityId', 'CUI', 'classificationCode', 'year', 'month'],
    scrapperRepoRelativePath: newLatest('src/sources/anaf-extranet/README.md'),
    experimentalDocs: [],
    newLatestPaths: [
      newLatest('src/sources/anaf-extranet/'),
      newLatest('src/sources/public-entities/'),
    ],
    clientFeaturePaths: [
      'src/components/budget-explorer/',
      'src/routes/',
      'src/lib/api/entities.ts',
    ],
    clientSchemaPaths: [
      'src/schemas/financial.ts',
      'src/schemas/entities.ts',
      'src/schemas/dataDiscovery.ts',
    ],
    clientSpecPaths: ['docs/user-stories/entity-details.md'],
    apiReady: true,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'ins-indicators',
    title: 'INS statistical indicators',
    description: 'INS Tempo-style indicators for map and chart series.',
    lifecycle: 'production',
    joinKeys: ['siruta_code', 'insSeriesId'],
    scrapperRepoRelativePath: experimental('geo-reference.md'),
    experimentalDocs: [experimental('geo-reference.md')],
    newLatestPaths: [],
    clientFeaturePaths: ['src/lib/api/ins.ts'],
    clientSchemaPaths: ['src/schemas/ins.ts'],
    clientSpecPaths: [
      'docs/specs/ins-api-technical.md',
      'docs/specs/ins-chart-series-api-requirements.md',
    ],
    apiReady: true,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'private-companies-onrc',
    title: 'Private companies — ONRC open data',
    description:
      'Company identity, status, CAEN authorization, representatives, branches.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'COD_INMATRICULARE'],
    scrapperRepoRelativePath: experimental('onrc.md'),
    experimentalDocs: [
      experimental('onrc.md'),
      'experimental/config/onrc-schema-baselines.json',
    ],
    newLatestPaths: [newLatest('src/sources/private-companies/')],
    clientFeaturePaths: ['src/features/private-companies/'],
    clientSchemaPaths: ['src/schemas/private-company.ts'],
    clientSpecPaths: ['docs/user-stories/private-company-details.md'],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'private-companies-anaf',
    title: 'Private companies — ANAF public fiscal',
    description: 'TVA status and bilant indicators for company CUIs.',
    lifecycle: 'loading',
    joinKeys: ['CUI'],
    scrapperRepoRelativePath: experimental('anaf.md'),
    experimentalDocs: [
      experimental('anaf.md'),
      'experimental/config/anaf-response-baselines.json',
    ],
    newLatestPaths: [newLatest('src/sources/private-companies/')],
    clientFeaturePaths: ['src/features/private-companies/'],
    clientSchemaPaths: ['src/schemas/private-company.ts'],
    clientSpecPaths: ['docs/user-stories/private-company-details.md'],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'public-contracts-seap',
    title: 'Public procurement — SEAP/SICAP',
    description:
      'Contracts, awards, direct acquisitions, modifications across SEAP families.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'CPV', 'contractNumber'],
    scrapperRepoRelativePath: experimental('seap.md'),
    experimentalDocs: [
      experimental('seap.md'),
      experimental('seap-workload-strategy.md'),
      experimental('seap-contracts.md'),
      experimental('seap-modifications.md'),
    ],
    newLatestPaths: [newLatest('src/sources/public-contracts/')],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'pnrr-projects',
    title: 'PNRR projects and payments',
    description:
      'Official PNRR project slices, beneficiaries, payments, and map analytics.',
    lifecycle: 'production',
    joinKeys: ['cui', 'id_angajament', 'cod_componenta', 'cod_masura'],
    scrapperRepoRelativePath: newLatest('src/sources/pnrr/'),
    experimentalDocs: [
      experimental('public-investments/pnrr-dataset-extraction-review-2026-05-18.md'),
      experimental('public-investments/pnrr-preliminary-source-extraction-architecture-2026-05-18.md'),
    ],
    newLatestPaths: [newLatest('src/sources/pnrr/')],
    clientFeaturePaths: ['src/features/pnrr/'],
    clientSchemaPaths: ['src/schemas/pnrr.ts'],
    clientSpecPaths: [
      'docs/specs/specs-202605042242-pnrr-official-project-data-model.md',
      'docs/PNRR-DASHBOARD-IMPLEMENTATION.md',
    ],
    apiReady: true,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'investments-anghel-saligny',
    title: 'Public investments — Anghel Saligny',
    description: 'MDLPA Anghel Saligny status, payments, and progress events.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA', 'projectId', 'CUI'],
    scrapperRepoRelativePath: experimental('public-investments/anghel-saligny.md'),
    experimentalDocs: [
      experimental('public-investments/anghel-saligny.md'),
      experimental('public-investments/workload-strategy.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'investments-pndl',
    title: 'Public investments — PNDL',
    description: 'PNDL history and CKAN DataStore resources keyed by SIRUTA.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA'],
    scrapperRepoRelativePath: experimental('public-investments/pndl.md'),
    experimentalDocs: [experimental('public-investments/pndl.md')],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-amepip',
    title: 'State-owned enterprises — AMEPIP core',
    description: 'OUG 109 public enterprise registry seed with CUI and tickers.',
    lifecycle: 'experimental',
    joinKeys: ['CUI', 'ticker', 'ISIN'],
    scrapperRepoRelativePath: experimental('soe/core-amepip.md'),
    experimentalDocs: [
      experimental('soe/core-amepip.md'),
      experimental('soe/workload-strategy.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-regas-state-aid',
    title: 'State-owned enterprises — RegAS state aid',
    description: 'RegAS transparenta API exact-CUI state-aid exposure.',
    lifecycle: 'experimental',
    joinKeys: ['CUI'],
    scrapperRepoRelativePath: experimental('soe/public-money.md'),
    experimentalDocs: [
      experimental('soe/public-money.md'),
      experimental('soe/profile-v2.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'ngo-core',
    title: 'NGOs — registry, CUI, and sector anchors',
    description:
      'Backend-only NGO v1 now loads ANOFM, ARACIP, and CNAS evidence into Griffin; PNRR/SMIS, SEAP, RegAS, CNA, and broad AEP remain related external datasources.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'SIRUTA'],
    scrapperRepoRelativePath: newLatest('docs/UNICORN_NGOS.md'),
    experimentalDocs: [
      experimental('ngo/extraction-readiness-2026-05-21.md'),
      experimental('ngo/additional-source-research-2026-05-21.md'),
      experimental('ngo/workload-strategy.md'),
      experimental('ngo/core-mj-registry.md'),
      experimental('ngo/anaf-fiscal-status.md'),
      experimental('ngo/public-money-grants.md'),
    ],
    newLatestPaths: [
      newLatest('docs/UNICORN_NGOS.md'),
      newLatest('src/sources/ngos/'),
    ],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'legal-portal-legislativ',
    title: 'Legal — Portal Legislativ',
    description:
      'National legal acts, status, relationships, summaries, and structured text.',
    lifecycle: 'loading',
    joinKeys: ['actId', 'displayCitation', 'canonicalDocumentId', 'CELEX'],
    scrapperRepoRelativePath: experimental('legal/portal-legislativ.md'),
    experimentalDocs: [
      experimental('legal/portal-legislativ.md'),
      experimental('legal/api-endpoints.md'),
      experimental('legal/law-index-sync.md'),
    ],
    newLatestPaths: [newLatest('src/sources/portal-legislativ/')],
    clientFeaturePaths: ['src/features/legal/'],
    clientSchemaPaths: ['src/schemas/legal.ts'],
    clientSpecPaths: [
      'docs/design/legal/ux.md',
      'docs/design/legal/design.md',
      'docs/design/legal/features/act-detail-status-summary.md',
      'docs/design/legal/features/legal-landing-page.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'legal-monitorul-oficial',
    title: 'Legal — Monitorul Oficial',
    description:
      'Official Gazette issue metadata, publication coordinates, PDF custody, and text-coverage state.',
    lifecycle: 'loading',
    joinKeys: ['issueId', 'partCode', 'issueNumber', 'issueDate', 'actId'],
    scrapperRepoRelativePath: experimental('legal/monitorul-oficial.md'),
    experimentalDocs: [
      experimental('legal/monitorul-oficial.md'),
      experimental('legal/law-index-sync.md'),
      experimental('legal/normative-act-lifecycle-state-machines.md'),
    ],
    newLatestPaths: [newLatest('src/sources/monitorul-oficial/')],
    clientFeaturePaths: ['src/features/legal/'],
    clientSchemaPaths: ['src/schemas/legal.ts'],
    clientSpecPaths: [
      'docs/design/legal/ux.md',
      'docs/design/legal/design.md',
      'docs/design/legal/features/monitorul-publication-card.md',
      'docs/design/legal/features/legal-landing-page.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'legal-judicial-cases',
    title: 'Legal — judicial cases (Portal Just)',
    description: 'Court case search metadata and dossier references.',
    lifecycle: 'loading',
    joinKeys: ['dosarId'],
    scrapperRepoRelativePath: experimental('legal/judicial-data.md'),
    experimentalDocs: [experimental('legal/judicial-data.md')],
    newLatestPaths: [newLatest('src/sources/judicial-cases/')],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'political-parliament',
    title: 'Political — parliament',
    description: 'Chamber/Senate members, groups, votes, and profiles.',
    lifecycle: 'loading',
    joinKeys: ['memberId', 'groupId', 'voteId'],
    scrapperRepoRelativePath: experimental('political/parliament.md'),
    experimentalDocs: [
      experimental('political/parliament.md'),
      experimental('political/workload-strategy.md'),
    ],
    newLatestPaths: [newLatest('src/sources/parliament/')],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'political-map-schema',
    title: 'Political — map administration schema',
    description:
      'Proposed political facts keyed by siruta_code for Advanced Map providers.',
    lifecycle: 'experimental',
    joinKeys: ['siruta_code', 'contestId', 'organizationId'],
    scrapperRepoRelativePath:
      experimental('political/political-administration-schema-proposal.md'),
    experimentalDocs: [
      experimental('political/political-administration-schema-proposal.md'),
      experimental('political/political-administration-schema-proposal.sql'),
      experimental('political/elections-candidates.md'),
      experimental('political/finance.md'),
      experimental('political/declarations.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/advanced-map-analytics/'],
    clientSchemaPaths: ['src/schemas/advanced-map-analytics.ts'],
    clientSpecPaths: [
      'docs/specs/specs-202605041809-map-grouping-domains-and-series.md',
    ],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'news-cna-licenses',
    title: 'News — CNA audiovisual licenses',
    description: 'TV/radio/VOD license tables and ownership prose from CNA PDFs.',
    lifecycle: 'experimental',
    joinKeys: ['licenseDocumentHash', 'outletUrl'],
    scrapperRepoRelativePath: experimental('news/cna-audiovisual.md'),
    experimentalDocs: [
      experimental('news/cna-audiovisual.md'),
      experimental('news/workload-strategy.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
] as const

export function getScraperDatasetById(
  datasetId: string,
): ScraperDatasetReference | undefined {
  return scraperDatasetCatalog.find((entry) => entry.id === datasetId)
}

export function listScraperDatasetsByLifecycle(
  lifecycle: ScraperDatasetReference['lifecycle'],
): readonly ScraperDatasetReference[] {
  return scraperDatasetCatalog.filter((entry) => entry.lifecycle === lifecycle)
}

export function listMockFirstDatasets(): readonly ScraperDatasetReference[] {
  return scraperDatasetCatalog.filter(
    (entry) => !entry.apiReady || entry.lifecycle !== 'production',
  )
}
