import type { ScraperDatasetReference } from './types'

const experimental = (path: string) => `experimental/docs/${path}`
const newLatest = (path: string) => `new_latest/${path}`
const prodDb = (path: string) => `prod-db/${path}`

export const scraperDatasetCatalog: readonly ScraperDatasetReference[] = [
  {
    id: 'reference-codes',
    title: 'Reference codes (SIRUTA, CAEN, CPV, ANCPI)',
    description:
      'Shared join spine for geography, activity, and procurement classification.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA', 'CAEN', 'CPV', 'NUTS'],
    scrapperRepoRelativePath: experimental('reference-code-contracts.md'),
    experimentalDocs: [
      experimental('reference-code-contracts.md'),
      experimental('join-key-matrix.md'),
      experimental('geo-reference.md'),
    ],
    newLatestPaths: [
      newLatest('docs/PRODUCTION_DATASET_SYSTEM_SPEC.md'),
      newLatest('docs/PRODUCTION_DATASET_VALIDATION.md'),
      newLatest('docs/production-dataset-serving-schema.sql'),
      newLatest('docs/production-dataset-validation-import.sql'),
    ],
    clientFeaturePaths: ['src/lib/api/map-series.ts', 'src/components/maps/'],
    clientSchemaPaths: ['src/schemas/entities.ts', 'src/schemas/map-filters.ts'],
    clientSpecPaths: [],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'budget-execution',
    title: 'Budget execution (ANAF extranet)',
    description: 'Core public budget income/expense data for entities and UATs.',
    lifecycle: 'production',
    joinKeys: ['entityId', 'CUI', 'classificationCode', 'year', 'month'],
    scrapperRepoRelativePath: newLatest('src/sources/anaf-extranet/README.md'),
    experimentalDocs: [],
    newLatestPaths: [
      newLatest('src/sources/anaf-extranet/'),
      newLatest('src/sources/public-entities/'),
    ],
    clientFeaturePaths: [
      'src/components/budget-explorer/',
      'src/routes/',
      'src/lib/api/entities.ts',
    ],
    clientSchemaPaths: [
      'src/schemas/financial.ts',
      'src/schemas/entities.ts',
      'src/schemas/dataDiscovery.ts',
    ],
    clientSpecPaths: ['docs/user-stories/entity-details.md'],
    apiReady: true,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'ins-indicators',
    title: 'INS statistical indicators',
    description: 'INS Tempo-style indicators for map and chart series.',
    lifecycle: 'production',
    joinKeys: ['siruta_code', 'insSeriesId'],
    scrapperRepoRelativePath: experimental('geo-reference.md'),
    experimentalDocs: [experimental('geo-reference.md')],
    newLatestPaths: [],
    clientFeaturePaths: ['src/lib/api/ins.ts', 'src/features/statistics/'],
    clientSchemaPaths: ['src/schemas/ins.ts', 'src/schemas/statistics.ts'],
    clientSpecPaths: [
      'docs/specs/ins-api-technical.md',
      'docs/specs/ins-chart-series-api-requirements.md',
    ],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'private-companies-onrc',
    title: 'Private companies — ONRC open data',
    description:
      'Company identity, status, CAEN authorization, representatives, branches.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'COD_INMATRICULARE'],
    scrapperRepoRelativePath: experimental('onrc.md'),
    experimentalDocs: [
      experimental('onrc.md'),
      'experimental/config/onrc-schema-baselines.json',
    ],
    newLatestPaths: [newLatest('src/sources/private-companies/')],
    clientFeaturePaths: ['src/features/private-companies/'],
    clientSchemaPaths: ['src/schemas/private-company.ts'],
    clientSpecPaths: ['docs/user-stories/private-company-details.md'],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'private-companies-anaf',
    title: 'Private companies — ANAF public fiscal',
    description: 'TVA status and bilant indicators for company CUIs.',
    lifecycle: 'loading',
    joinKeys: ['CUI'],
    scrapperRepoRelativePath: experimental('anaf.md'),
    experimentalDocs: [
      experimental('anaf.md'),
      'experimental/config/anaf-response-baselines.json',
    ],
    newLatestPaths: [newLatest('src/sources/private-companies/')],
    clientFeaturePaths: ['src/features/private-companies/'],
    clientSchemaPaths: ['src/schemas/private-company.ts'],
    clientSpecPaths: ['docs/user-stories/private-company-details.md'],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'public-contracts-seap',
    title: 'Public procurement — SEAP/SICAP',
    description:
      'Contracts, awards, direct acquisitions, modifications across SEAP families.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'CPV', 'contractNumber'],
    scrapperRepoRelativePath: experimental('seap.md'),
    experimentalDocs: [
      experimental('seap.md'),
      experimental('seap-workload-strategy.md'),
      experimental('seap-contracts.md'),
      experimental('seap-modifications.md'),
    ],
    newLatestPaths: [newLatest('src/sources/public-contracts/')],
    clientFeaturePaths: [
      'src/features/procurement/',
      'src/routes/procurement/',
    ],
    clientSchemaPaths: [
      'src/schemas/procurement.ts',
      'src/schemas/procurement-search.ts',
    ],
    clientSpecPaths: [
      'docs/design/procurement/ux.md',
      'docs/design/procurement/design.md',
      'docs/design/procurement/features/procurement-search-listing.md',
      'docs/design/procurement/features/procurement-record-detail-pages.md',
      'docs/design/procurement/features/cpv-category-page.md',
      'docs/design/procurement/features/supplier-procurement-slice.md',
      'docs/design/procurement/features/coverage-data-as-of-layer.md',
    ],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'pnrr-projects',
    title: 'PNRR projects and payments',
    description:
      'Official PNRR project slices, beneficiaries, payments, and map analytics.',
    lifecycle: 'production',
    joinKeys: ['cui', 'id_angajament', 'cod_componenta', 'cod_masura'],
    scrapperRepoRelativePath: newLatest('src/sources/pnrr/'),
    experimentalDocs: [
      experimental('public-investments/pnrr-dataset-extraction-review-2026-05-18.md'),
      experimental('public-investments/pnrr-preliminary-source-extraction-architecture-2026-05-18.md'),
    ],
    newLatestPaths: [newLatest('src/sources/pnrr/')],
    clientFeaturePaths: ['src/features/pnrr/'],
    clientSchemaPaths: ['src/schemas/pnrr.ts'],
    clientSpecPaths: [
      'docs/specs/specs-202605042242-pnrr-official-project-data-model.md',
      'docs/PNRR-DASHBOARD-IMPLEMENTATION.md',
    ],
    apiReady: true,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'public-investments',
    title: 'Public investments — feature umbrella',
    description:
      'Mock-first public investments surface that combines Anghel Saligny, PNDL, and backlog investment lanes behind one client feature gate.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA', 'CUI', 'projectId', 'programCode'],
    scrapperRepoRelativePath: experimental('public-investments/workload-strategy.md'),
    experimentalDocs: [
      experimental('public-investments/workload-strategy.md'),
      experimental('public-investments/anghel-saligny.md'),
      experimental('public-investments/pndl.md'),
      experimental('public-investments/datelocale.md'),
      experimental('public-investments/mdlpa-platforms.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [
      'src/features/public-investments/',
      'src/routes/investitii-publice/',
    ],
    clientSchemaPaths: ['src/schemas/public-investments.ts'],
    clientSpecPaths: [
      'docs/design/public-investments/ux.md',
      'docs/design/public-investments/design.md',
      'docs/design/public-investments/features/objectives-map-landing.md',
      'docs/design/public-investments/features/objectives-search-listing.md',
      'docs/design/public-investments/features/locality-county-page.md',
      'docs/design/public-investments/features/objective-detail-hub.md',
      'docs/design/public-investments/features/evidence-viewer.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'investments-anghel-saligny',
    title: 'Public investments — Anghel Saligny',
    description: 'MDLPA Anghel Saligny status, payments, and progress events.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA', 'projectId', 'CUI'],
    scrapperRepoRelativePath: experimental('public-investments/anghel-saligny.md'),
    experimentalDocs: [
      experimental('public-investments/anghel-saligny.md'),
      experimental('public-investments/workload-strategy.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/public-investments/'],
    clientSchemaPaths: ['src/schemas/public-investments.ts'],
    clientSpecPaths: [
      'docs/design/public-investments/ux.md',
      'docs/design/public-investments/features/objectives-search-listing.md',
      'docs/design/public-investments/features/objective-detail-hub.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'investments-pndl',
    title: 'Public investments — PNDL',
    description: 'PNDL history and CKAN DataStore resources keyed by SIRUTA.',
    lifecycle: 'experimental',
    joinKeys: ['SIRUTA'],
    scrapperRepoRelativePath: experimental('public-investments/pndl.md'),
    experimentalDocs: [experimental('public-investments/pndl.md')],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/public-investments/'],
    clientSchemaPaths: ['src/schemas/public-investments.ts'],
    clientSpecPaths: [
      'docs/design/public-investments/ux.md',
      'docs/design/public-investments/features/objectives-search-listing.md',
      'docs/design/public-investments/features/locality-county-page.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'soe-amepip',
    title: 'Public enterprises — AMEPIP registry and indicators',
    description:
      'OUG 109 AMEPIP company-year and form registries (primary membership) and their indicator cells as exact decimal text, served live by the public-enterprises GraphQL module.',
    lifecycle: 'loading',
    joinKeys: ['CUI'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/public-enterprises/'],
    clientSchemaPaths: [],
    clientSpecPaths: ['docs/design/public-companies/design.md'],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-controlling-authority',
    title: 'Public enterprises — S1001 list and authority links',
    description:
      'ANAF S1001 list (primary membership) and the S1001/JSON-APT control edges as each source reports them, served live by the public-enterprises GraphQL module. A control edge is not an ownership claim.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'APT CUI'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_AUTHORITY_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/public-enterprises/'],
    clientSchemaPaths: [],
    clientSpecPaths: ['docs/design/public-companies/design.md'],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-regas-state-aid',
    title: 'Public enterprises — RegAS state aid',
    description:
      'RegAS exact-CUI state-aid awards, loaded in the production database but not served by the API (no client surface).',
    lifecycle: 'loading',
    joinKeys: ['CUI'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_REGAS_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: ['docs/design/public-companies/features/state-aid-tab.md'],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-bvb-market',
    title: 'Public enterprises — BVB listings and reports',
    description:
      'BVB issuers, tickers and report metadata for listed public enterprises, loaded in the production database but not served by the API (no client surface).',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'ticker', 'ISIN'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_BVB_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [
      'docs/design/public-companies/features/bvb-market-reports-tab.md',
    ],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'soe-sanctions',
    title: 'Public enterprises — AMEPIP sanctions',
    description:
      'AMEPIP OUG 109 sanctions and enforcement rows, loaded in the production database but not served by the API (no client surface); the responsible-person text is never public.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'APT CUI'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_SANCTIONS_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [
      'docs/design/public-companies/features/sanctions-enforcement-tab.md',
    ],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'soe-governance-docs',
    title: 'Public enterprises — governance documents',
    description:
      'AMEPIP JSON-APT governance document index, loaded in the production database but not served by the API (no client surface); listing is not capture, capture is not parsed facts.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'APT CUI', 'document URL'],
    scrapperRepoRelativePath: prodDb('PUBLIC_COMPANIES_NOTES.md'),
    experimentalDocs: [],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [
      'docs/design/public-companies/features/governance-document-viewer.md',
    ],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'ngo-core',
    title: 'NGOs — registry, CUI, and sector anchors',
    description:
      'NGO hub, registry and profiles over the national NGO registry, ANAF and MFP statements, anchored on CUI and registry number; social services, source provenance and public funding are planned, with no mock surface.',
    lifecycle: 'loading',
    joinKeys: ['CUI', 'SIRUTA'],
    scrapperRepoRelativePath: prodDb('NGOS_NOTES.md'),
    experimentalDocs: [
      experimental('ngo/extraction-readiness-2026-05-21.md'),
      experimental('ngo/additional-source-research-2026-05-21.md'),
      experimental('ngo/workload-strategy.md'),
      experimental('ngo/core-mj-registry.md'),
      experimental('ngo/anaf-fiscal-status.md'),
      experimental('ngo/public-money-grants.md'),
    ],
    newLatestPaths: [
      newLatest('docs/UNICORN_NGOS.md'),
      newLatest('src/sources/ngos/'),
    ],
    clientFeaturePaths: ['src/features/ngos/', 'src/routes/ngos/'],
    clientSchemaPaths: ['src/schemas/ngos.ts'],
    clientSpecPaths: [
      'docs/design/ngos/ux.md',
      'docs/design/ngos/design.md',
      'docs/design/ngos/features/ngo-landing-source-coverage.md',
      'docs/design/ngos/features/ngo-entity-profile.md',
      'docs/design/ngos/features/social-service-provider-discovery.md',
      'docs/design/ngos/features/evidence-trail-source-citations.md',
      'docs/design/ngos/features/public-funding-cross-links.md',
    ],
    apiReady: true,
    mockDataAvailable: false,
    privacySensitive: false,
  },
  {
    id: 'legal-acts',
    title: 'Legal — normative acts (Portal Legislativ + Monitorul Oficial)',
    description:
      'Romanian legal acts with status, citation graph, plain-language summaries, and Official Gazette publication evidence.',
    lifecycle: 'production',
    joinKeys: ['actId', 'actNaturalKey', 'moIssueId'],
    scrapperRepoRelativePath: prodDb('LEGAL_CONTRACT.md'),
    experimentalDocs: [],
    newLatestPaths: [
      prodDb('LEGAL_CONTRACT.md'),
      prodDb('LEGAL_CURRENT_STATE.md'),
      prodDb('LEGAL_DATA_BRIEF.md'),
      prodDb('LEGAL_SCHEMA_DESIGN.md'),
      prodDb('MONITORUL_NOTES.md'),
      prodDb('PORTAL_LEGISLATIV_NOTES.md'),
    ],
    clientFeaturePaths: ['src/features/legal/', 'src/routes/legislation/'],
    clientSchemaPaths: ['src/schemas/legal.ts'],
    clientSpecPaths: [
      'docs/design/legal/main-page.md',
      'docs/design/legal/act-detail.md',
      'docs/design/legal/design.md',
      'docs/design/legal/ux.md',
    ],
    // Partly wired: `legal-act-api.live.ts` serves `/legislation/acts/$actId`
    // from the real `legalAct` query, but the overview's live lane is still a
    // stub. Flip to `true` when `legal-api.live.ts` lands — see
    // docs/design/legal/main-page.md §5.
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: false,
  },
  {
    id: 'political-parliament',
    title: 'Political — parliament',
    description: 'Chamber/Senate members, groups, votes, profiles, and legislative bills.',
    lifecycle: 'loading',
    joinKeys: ['memberId', 'groupId', 'voteId', 'billId'],
    scrapperRepoRelativePath: experimental('political/parliament.md'),
    experimentalDocs: [
      experimental('political/parliament.md'),
      experimental('political/workload-strategy.md'),
    ],
    newLatestPaths: [newLatest('src/sources/parliament/')],
    clientFeaturePaths: ['src/features/parliament/'],
    clientSchemaPaths: ['src/schemas/parliament.ts'],
    clientSpecPaths: [
      'docs/specs/parlament-design-principles.md',
      'docs/user-stories/parlament.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
  {
    id: 'political-map-schema',
    title: 'Political — map administration schema',
    description:
      'Proposed political facts keyed by siruta_code for Advanced Map providers.',
    lifecycle: 'experimental',
    joinKeys: ['siruta_code', 'contestId', 'organizationId'],
    scrapperRepoRelativePath:
      experimental('political/political-administration-schema-proposal.md'),
    experimentalDocs: [
      experimental('political/political-administration-schema-proposal.md'),
      experimental('political/political-administration-schema-proposal.sql'),
      experimental('political/elections-candidates.md'),
      experimental('political/finance.md'),
      experimental('political/declarations.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/advanced-map-analytics/'],
    clientSchemaPaths: ['src/schemas/advanced-map-analytics.ts'],
    clientSpecPaths: [
      'docs/specs/specs-202605041809-map-grouping-domains-and-series.md',
    ],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'news-cna-licenses',
    title: 'News — CNA audiovisual licenses',
    description: 'TV/radio/VOD license tables and ownership prose from CNA PDFs.',
    lifecycle: 'experimental',
    joinKeys: ['licenseDocumentHash', 'outletUrl'],
    scrapperRepoRelativePath: experimental('news/cna-audiovisual.md'),
    experimentalDocs: [
      experimental('news/cna-audiovisual.md'),
      experimental('news/workload-strategy.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: [],
    clientSchemaPaths: [],
    clientSpecPaths: [],
    apiReady: false,
    mockDataAvailable: false,
    privacySensitive: true,
  },
  {
    id: 'elections',
    title: 'Election results (AEP/BEC/ROAEP)',
    description:
      'Romanian public election results 1992–2025 (local, parliamentary, presidential, European Parliament, referendum): contests, reporting units, competitors, candidacies, mandates, and per-row source pointers.',
    lifecycle: 'loading',
    joinKeys: [
      'electionKey',
      'contestKey',
      'reportingUnitKey',
      'competitorKey',
      'candidateKey',
      'sourceResourceId',
      'sirutaCode',
    ],
    scrapperRepoRelativePath: prodDb('ELECTIONS_NOTES.md'),
    experimentalDocs: [
      experimental('political/elections-candidates.md'),
      experimental('political/political-administration-schema-proposal.md'),
    ],
    newLatestPaths: [],
    clientFeaturePaths: ['src/features/elections/'],
    clientSchemaPaths: ['src/schemas/elections.ts'],
    clientSpecPaths: [
      'docs/design/elections/ux.md',
      'docs/design/elections/design.md',
      'docs/design/elections/features/contest-result-explorer.md',
      'docs/design/elections/features/elections-landing-browse.md',
      'docs/design/elections/features/source-provenance-drawer.md',
    ],
    apiReady: false,
    mockDataAvailable: true,
    privacySensitive: true,
  },
] as const

export function getScraperDatasetById(
  datasetId: string,
): ScraperDatasetReference | undefined {
  return scraperDatasetCatalog.find((entry) => entry.id === datasetId)
}

export function listScraperDatasetsByLifecycle(
  lifecycle: ScraperDatasetReference['lifecycle'],
): readonly ScraperDatasetReference[] {
  return scraperDatasetCatalog.filter((entry) => entry.lifecycle === lifecycle)
}

export function listMockFirstDatasets(): readonly ScraperDatasetReference[] {
  return scraperDatasetCatalog.filter(
    (entry) => !entry.apiReady || entry.lifecycle !== 'production',
  )
}
