/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as EntityAnalyticsRouteImport } from './routes/entity-analytics'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as BudgetExplorerRouteImport } from './routes/budget-explorer'
import { Route as BugetPrimarieRouteRouteImport } from './routes/buget-primarie/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugetPrimarieIndexRouteImport } from './routes/buget-primarie/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as ShareCodeRouteImport } from './routes/share.$code'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as EntitiesCuiRouteImport } from './routes/entities.$cui'
import { Route as ChartsNewRouteImport } from './routes/charts/new'
import { Route as CertificatesIdRouteImport } from './routes/certificates.$id'
import { Route as BugetPrimarieForumRouteImport } from './routes/buget-primarie/forum'
import { Route as AlertsNewRouteImport } from './routes/alerts/new'
import { Route as ChartsChartIdRouteRouteImport } from './routes/charts/$chartId/route'
import { Route as BugetPrimarieCuiRouteRouteImport } from './routes/buget-primarie/$cui/route'
import { Route as AlertsAlertIdRouteRouteImport } from './routes/alerts/$alertId/route'
import { Route as LangLearningRouteRouteImport } from './routes/$lang/learning/route'
import { Route as MapsEditorIndexRouteImport } from './routes/maps/editor/index'
import { Route as ClassificationsFunctionalIndexRouteImport } from './routes/classifications/functional/index'
import { Route as ClassificationsEconomicIndexRouteImport } from './routes/classifications/economic/index'
import { Route as BugetPrimarieCautaIndexRouteImport } from './routes/buget-primarie/cauta/index'
import { Route as LangLearningIndexRouteImport } from './routes/$lang/learning/index'
import { Route as MapsPublicMapIdRouteImport } from './routes/maps/public/$mapId'
import { Route as MapsEditorNewRouteImport } from './routes/maps/editor/new'
import { Route as MapsEditorMapIdRouteImport } from './routes/maps/editor/$mapId'
import { Route as EntitiesCuiShareImageDotpngRouteImport } from './routes/entities.$cui.share-image[.]png'
import { Route as ClassificationsFunctionalCodeRouteImport } from './routes/classifications/functional/$code'
import { Route as ClassificationsEconomicCodeRouteImport } from './routes/classifications/economic/$code'
import { Route as BugetPrimarieCuiPrimarieRouteImport } from './routes/buget-primarie/$cui/primarie'
import { Route as BugetPrimarieCuiCalendarRouteImport } from './routes/buget-primarie/$cui/calendar'
import { Route as LangLearningOnboardingRouteImport } from './routes/$lang/learning/onboarding'
import { Route as BugetPrimarieCuiProvocariRouteRouteImport } from './routes/buget-primarie/$cui/provocari/route'
import { Route as BugetPrimarieCautaHartaIndexRouteImport } from './routes/buget-primarie/cauta/harta/index'
import { Route as BugetPrimarieCuiProvocariIndexRouteImport } from './routes/buget-primarie/$cui/provocari/index'
import { Route as LangLearningPathIdIndexRouteImport } from './routes/$lang/learning/$pathId/index'
import { Route as LangLearningCertificatesIdRouteImport } from './routes/$lang/learning/certificates.$id'
import { Route as BugetPrimarieCuiProvocariModuleSlugIndexRouteImport } from './routes/buget-primarie/$cui/provocari/$moduleSlug/index'
import { Route as LangLearningPathIdModuleIdLessonIdRouteImport } from './routes/$lang/learning/$pathId/$moduleId/$lessonId'
import { Route as BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRouteImport } from './routes/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'

const TermsLazyRouteImport = createFileRoute('/terms')()
const ChartsIndexLazyRouteImport = createFileRoute('/charts/')()
const ResearchEmployeesDataLazyRouteImport = createFileRoute(
  '/research/employees-data',
)()
const ChartsChartIdIndexLazyRouteImport = createFileRoute('/charts/$chartId/')()
const AlertsAlertIdIndexLazyRouteImport = createFileRoute('/alerts/$alertId/')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))
const EntityAnalyticsRoute = EntityAnalyticsRouteImport.update({
  id: '/entity-analytics',
  path: '/entity-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/entity-analytics.lazy').then((d) => d.Route),
)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookie-policy.lazy').then((d) => d.Route))
const BudgetExplorerRoute = BudgetExplorerRouteImport.update({
  id: '/budget-explorer',
  path: '/budget-explorer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/budget-explorer.lazy').then((d) => d.Route),
)
const BugetPrimarieRouteRoute = BugetPrimarieRouteRouteImport.update({
  id: '/buget-primarie',
  path: '/buget-primarie',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/buget-primarie/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIndexLazyRoute = ChartsIndexLazyRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts/index.lazy').then((d) => d.Route))
const BugetPrimarieIndexRoute = BugetPrimarieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BugetPrimarieRouteRoute,
} as any).lazy(() =>
  import('./routes/buget-primarie/index.lazy').then((d) => d.Route),
)
const ResearchEmployeesDataLazyRoute =
  ResearchEmployeesDataLazyRouteImport.update({
    id: '/research/employees-data',
    path: '/research/employees-data',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/research/employees-data.lazy').then((d) => d.Route),
  )
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCodeRoute = ShareCodeRouteImport.update({
  id: '/share/$code',
  path: '/share/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesCuiRoute = EntitiesCuiRouteImport.update({
  id: '/entities/$cui',
  path: '/entities/$cui',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/entities.$cui.lazy').then((d) => d.Route))
const ChartsNewRoute = ChartsNewRouteImport.update({
  id: '/charts/new',
  path: '/charts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdRoute = CertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BugetPrimarieForumRoute = BugetPrimarieForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => BugetPrimarieRouteRoute,
} as any).lazy(() =>
  import('./routes/buget-primarie/forum.lazy').then((d) => d.Route),
)
const AlertsNewRoute = AlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerts/new.lazy').then((d) => d.Route))
const ChartsChartIdRouteRoute = ChartsChartIdRouteRouteImport.update({
  id: '/charts/$chartId',
  path: '/charts/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const BugetPrimarieCuiRouteRoute = BugetPrimarieCuiRouteRouteImport.update({
  id: '/$cui',
  path: '/$cui',
  getParentRoute: () => BugetPrimarieRouteRoute,
} as any).lazy(() =>
  import('./routes/buget-primarie/$cui/route.lazy').then((d) => d.Route),
)
const AlertsAlertIdRouteRoute = AlertsAlertIdRouteRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLearningRouteRoute = LangLearningRouteRouteImport.update({
  id: '/$lang/learning',
  path: '/$lang/learning',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$lang/learning/route.lazy').then((d) => d.Route),
)
const ChartsChartIdIndexLazyRoute = ChartsChartIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartsChartIdRouteRoute,
} as any).lazy(() =>
  import('./routes/charts/$chartId/index.lazy').then((d) => d.Route),
)
const AlertsAlertIdIndexLazyRoute = AlertsAlertIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsAlertIdRouteRoute,
} as any).lazy(() =>
  import('./routes/alerts/$alertId/index.lazy').then((d) => d.Route),
)
const MapsEditorIndexRoute = MapsEditorIndexRouteImport.update({
  id: '/maps/editor/',
  path: '/maps/editor/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/maps/editor/index.lazy').then((d) => d.Route),
)
const ClassificationsFunctionalIndexRoute =
  ClassificationsFunctionalIndexRouteImport.update({
    id: '/classifications/functional/',
    path: '/classifications/functional/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicIndexRoute =
  ClassificationsEconomicIndexRouteImport.update({
    id: '/classifications/economic/',
    path: '/classifications/economic/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/index.lazy').then((d) => d.Route),
  )
const BugetPrimarieCautaIndexRoute = BugetPrimarieCautaIndexRouteImport.update({
  id: '/cauta/',
  path: '/cauta/',
  getParentRoute: () => BugetPrimarieRouteRoute,
} as any).lazy(() =>
  import('./routes/buget-primarie/cauta/index.lazy').then((d) => d.Route),
)
const LangLearningIndexRoute = LangLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/index.lazy').then((d) => d.Route),
)
const MapsPublicMapIdRoute = MapsPublicMapIdRouteImport.update({
  id: '/maps/public/$mapId',
  path: '/maps/public/$mapId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/maps/public/$mapId.lazy').then((d) => d.Route),
)
const MapsEditorNewRoute = MapsEditorNewRouteImport.update({
  id: '/maps/editor/new',
  path: '/maps/editor/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/maps/editor/new.lazy').then((d) => d.Route),
)
const MapsEditorMapIdRoute = MapsEditorMapIdRouteImport.update({
  id: '/maps/editor/$mapId',
  path: '/maps/editor/$mapId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/maps/editor/$mapId.lazy').then((d) => d.Route),
)
const EntitiesCuiShareImageDotpngRoute =
  EntitiesCuiShareImageDotpngRouteImport.update({
    id: '/share-image.png',
    path: '/share-image.png',
    getParentRoute: () => EntitiesCuiRoute,
  } as any)
const ClassificationsFunctionalCodeRoute =
  ClassificationsFunctionalCodeRouteImport.update({
    id: '/classifications/functional/$code',
    path: '/classifications/functional/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/$code.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicCodeRoute =
  ClassificationsEconomicCodeRouteImport.update({
    id: '/classifications/economic/$code',
    path: '/classifications/economic/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/$code.lazy').then((d) => d.Route),
  )
const BugetPrimarieCuiPrimarieRoute =
  BugetPrimarieCuiPrimarieRouteImport.update({
    id: '/primarie',
    path: '/primarie',
    getParentRoute: () => BugetPrimarieCuiRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/$cui/primarie.lazy').then((d) => d.Route),
  )
const BugetPrimarieCuiCalendarRoute =
  BugetPrimarieCuiCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => BugetPrimarieCuiRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/$cui/calendar.lazy').then((d) => d.Route),
  )
const LangLearningOnboardingRoute = LangLearningOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/onboarding.lazy').then((d) => d.Route),
)
const BugetPrimarieCuiProvocariRouteRoute =
  BugetPrimarieCuiProvocariRouteRouteImport.update({
    id: '/provocari',
    path: '/provocari',
    getParentRoute: () => BugetPrimarieCuiRouteRoute,
  } as any)
const BugetPrimarieCautaHartaIndexRoute =
  BugetPrimarieCautaHartaIndexRouteImport.update({
    id: '/cauta/harta/',
    path: '/cauta/harta/',
    getParentRoute: () => BugetPrimarieRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/cauta/harta/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BugetPrimarieCuiProvocariIndexRoute =
  BugetPrimarieCuiProvocariIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BugetPrimarieCuiProvocariRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/$cui/provocari/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LangLearningPathIdIndexRoute = LangLearningPathIdIndexRouteImport.update({
  id: '/$pathId/',
  path: '/$pathId/',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/$pathId/index.lazy').then((d) => d.Route),
)
const LangLearningCertificatesIdRoute =
  LangLearningCertificatesIdRouteImport.update({
    id: '/certificates/$id',
    path: '/certificates/$id',
    getParentRoute: () => LangLearningRouteRoute,
  } as any).lazy(() =>
    import('./routes/$lang/learning/certificates.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const BugetPrimarieCuiProvocariModuleSlugIndexRoute =
  BugetPrimarieCuiProvocariModuleSlugIndexRouteImport.update({
    id: '/$moduleSlug/',
    path: '/$moduleSlug/',
    getParentRoute: () => BugetPrimarieCuiProvocariRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/$cui/provocari/$moduleSlug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LangLearningPathIdModuleIdLessonIdRoute =
  LangLearningPathIdModuleIdLessonIdRouteImport.update({
    id: '/$pathId/$moduleId/$lessonId',
    path: '/$pathId/$moduleId/$lessonId',
    getParentRoute: () => LangLearningRouteRoute,
  } as any).lazy(() =>
    import('./routes/$lang/learning/$pathId/$moduleId/$lessonId.lazy').then(
      (d) => d.Route,
    ),
  )
const BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute =
  BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRouteImport.update({
    id: '/$moduleSlug/$challengeSlug/$stepSlug',
    path: '/$moduleSlug/$challengeSlug/$stepSlug',
    getParentRoute: () => BugetPrimarieCuiProvocariRouteRoute,
  } as any).lazy(() =>
    import('./routes/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buget-primarie': typeof BugetPrimarieRouteRouteWithChildren
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/$lang/learning': typeof LangLearningRouteRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/buget-primarie/$cui': typeof BugetPrimarieCuiRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/buget-primarie/forum': typeof BugetPrimarieForumRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/buget-primarie/': typeof BugetPrimarieIndexRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/buget-primarie/$cui/provocari': typeof BugetPrimarieCuiProvocariRouteRouteWithChildren
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/buget-primarie/$cui/calendar': typeof BugetPrimarieCuiCalendarRoute
  '/buget-primarie/$cui/primarie': typeof BugetPrimarieCuiPrimarieRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/maps/editor/$mapId': typeof MapsEditorMapIdRoute
  '/maps/editor/new': typeof MapsEditorNewRoute
  '/maps/public/$mapId': typeof MapsPublicMapIdRoute
  '/$lang/learning/': typeof LangLearningIndexRoute
  '/buget-primarie/cauta/': typeof BugetPrimarieCautaIndexRoute
  '/classifications/economic/': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional/': typeof ClassificationsFunctionalIndexRoute
  '/maps/editor/': typeof MapsEditorIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId/': typeof LangLearningPathIdIndexRoute
  '/buget-primarie/$cui/provocari/': typeof BugetPrimarieCuiProvocariIndexRoute
  '/buget-primarie/cauta/harta/': typeof BugetPrimarieCautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
  '/buget-primarie/$cui/provocari/$moduleSlug/': typeof BugetPrimarieCuiProvocariModuleSlugIndexRoute
  '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug': typeof BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/buget-primarie/$cui': typeof BugetPrimarieCuiRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/buget-primarie/forum': typeof BugetPrimarieForumRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/buget-primarie': typeof BugetPrimarieIndexRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/buget-primarie/$cui/calendar': typeof BugetPrimarieCuiCalendarRoute
  '/buget-primarie/$cui/primarie': typeof BugetPrimarieCuiPrimarieRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/maps/editor/$mapId': typeof MapsEditorMapIdRoute
  '/maps/editor/new': typeof MapsEditorNewRoute
  '/maps/public/$mapId': typeof MapsPublicMapIdRoute
  '/$lang/learning': typeof LangLearningIndexRoute
  '/buget-primarie/cauta': typeof BugetPrimarieCautaIndexRoute
  '/classifications/economic': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional': typeof ClassificationsFunctionalIndexRoute
  '/maps/editor': typeof MapsEditorIndexRoute
  '/alerts/$alertId': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId': typeof LangLearningPathIdIndexRoute
  '/buget-primarie/$cui/provocari': typeof BugetPrimarieCuiProvocariIndexRoute
  '/buget-primarie/cauta/harta': typeof BugetPrimarieCautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
  '/buget-primarie/$cui/provocari/$moduleSlug': typeof BugetPrimarieCuiProvocariModuleSlugIndexRoute
  '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug': typeof BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buget-primarie': typeof BugetPrimarieRouteRouteWithChildren
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/$lang/learning': typeof LangLearningRouteRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/buget-primarie/$cui': typeof BugetPrimarieCuiRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/buget-primarie/forum': typeof BugetPrimarieForumRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/buget-primarie/': typeof BugetPrimarieIndexRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/buget-primarie/$cui/provocari': typeof BugetPrimarieCuiProvocariRouteRouteWithChildren
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/buget-primarie/$cui/calendar': typeof BugetPrimarieCuiCalendarRoute
  '/buget-primarie/$cui/primarie': typeof BugetPrimarieCuiPrimarieRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/maps/editor/$mapId': typeof MapsEditorMapIdRoute
  '/maps/editor/new': typeof MapsEditorNewRoute
  '/maps/public/$mapId': typeof MapsPublicMapIdRoute
  '/$lang/learning/': typeof LangLearningIndexRoute
  '/buget-primarie/cauta/': typeof BugetPrimarieCautaIndexRoute
  '/classifications/economic/': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional/': typeof ClassificationsFunctionalIndexRoute
  '/maps/editor/': typeof MapsEditorIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId/': typeof LangLearningPathIdIndexRoute
  '/buget-primarie/$cui/provocari/': typeof BugetPrimarieCuiProvocariIndexRoute
  '/buget-primarie/cauta/harta/': typeof BugetPrimarieCautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
  '/buget-primarie/$cui/provocari/$moduleSlug/': typeof BugetPrimarieCuiProvocariModuleSlugIndexRoute
  '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug': typeof BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buget-primarie'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/$lang/learning'
    | '/alerts/$alertId'
    | '/buget-primarie/$cui'
    | '/charts/$chartId'
    | '/alerts/new'
    | '/buget-primarie/forum'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/buget-primarie/'
    | '/charts/'
    | '/buget-primarie/$cui/provocari'
    | '/$lang/learning/onboarding'
    | '/buget-primarie/$cui/calendar'
    | '/buget-primarie/$cui/primarie'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/maps/editor/$mapId'
    | '/maps/editor/new'
    | '/maps/public/$mapId'
    | '/$lang/learning/'
    | '/buget-primarie/cauta/'
    | '/classifications/economic/'
    | '/classifications/functional/'
    | '/maps/editor/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId/'
    | '/buget-primarie/$cui/provocari/'
    | '/buget-primarie/cauta/harta/'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
    | '/buget-primarie/$cui/provocari/$moduleSlug/'
    | '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/buget-primarie/$cui'
    | '/alerts/new'
    | '/buget-primarie/forum'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/buget-primarie'
    | '/charts'
    | '/$lang/learning/onboarding'
    | '/buget-primarie/$cui/calendar'
    | '/buget-primarie/$cui/primarie'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/maps/editor/$mapId'
    | '/maps/editor/new'
    | '/maps/public/$mapId'
    | '/$lang/learning'
    | '/buget-primarie/cauta'
    | '/classifications/economic'
    | '/classifications/functional'
    | '/maps/editor'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId'
    | '/buget-primarie/$cui/provocari'
    | '/buget-primarie/cauta/harta'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
    | '/buget-primarie/$cui/provocari/$moduleSlug'
    | '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'
  id:
    | '__root__'
    | '/'
    | '/buget-primarie'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/$lang/learning'
    | '/alerts/$alertId'
    | '/buget-primarie/$cui'
    | '/charts/$chartId'
    | '/alerts/new'
    | '/buget-primarie/forum'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/buget-primarie/'
    | '/charts/'
    | '/buget-primarie/$cui/provocari'
    | '/$lang/learning/onboarding'
    | '/buget-primarie/$cui/calendar'
    | '/buget-primarie/$cui/primarie'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/maps/editor/$mapId'
    | '/maps/editor/new'
    | '/maps/public/$mapId'
    | '/$lang/learning/'
    | '/buget-primarie/cauta/'
    | '/classifications/economic/'
    | '/classifications/functional/'
    | '/maps/editor/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId/'
    | '/buget-primarie/$cui/provocari/'
    | '/buget-primarie/cauta/harta/'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
    | '/buget-primarie/$cui/provocari/$moduleSlug/'
    | '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugetPrimarieRouteRoute: typeof BugetPrimarieRouteRouteWithChildren
  BudgetExplorerRoute: typeof BudgetExplorerRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  EntityAnalyticsRoute: typeof EntityAnalyticsRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  TestErrorRoute: typeof TestErrorRoute
  TermsLazyRoute: typeof TermsLazyRoute
  LangLearningRouteRoute: typeof LangLearningRouteRouteWithChildren
  AlertsAlertIdRouteRoute: typeof AlertsAlertIdRouteRouteWithChildren
  ChartsChartIdRouteRoute: typeof ChartsChartIdRouteRouteWithChildren
  AlertsNewRoute: typeof AlertsNewRoute
  CertificatesIdRoute: typeof CertificatesIdRoute
  ChartsNewRoute: typeof ChartsNewRoute
  EntitiesCuiRoute: typeof EntitiesCuiRouteWithChildren
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ShareCodeRoute: typeof ShareCodeRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ResearchEmployeesDataLazyRoute: typeof ResearchEmployeesDataLazyRoute
  ChartsIndexLazyRoute: typeof ChartsIndexLazyRoute
  ClassificationsEconomicCodeRoute: typeof ClassificationsEconomicCodeRoute
  ClassificationsFunctionalCodeRoute: typeof ClassificationsFunctionalCodeRoute
  MapsEditorMapIdRoute: typeof MapsEditorMapIdRoute
  MapsEditorNewRoute: typeof MapsEditorNewRoute
  MapsPublicMapIdRoute: typeof MapsPublicMapIdRoute
  ClassificationsEconomicIndexRoute: typeof ClassificationsEconomicIndexRoute
  ClassificationsFunctionalIndexRoute: typeof ClassificationsFunctionalIndexRoute
  MapsEditorIndexRoute: typeof MapsEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity-analytics': {
      id: '/entity-analytics'
      path: '/entity-analytics'
      fullPath: '/entity-analytics'
      preLoaderRoute: typeof EntityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-explorer': {
      id: '/budget-explorer'
      path: '/budget-explorer'
      fullPath: '/budget-explorer'
      preLoaderRoute: typeof BudgetExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie': {
      id: '/buget-primarie'
      path: '/buget-primarie'
      fullPath: '/buget-primarie'
      preLoaderRoute: typeof BugetPrimarieRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie/': {
      id: '/buget-primarie/'
      path: '/'
      fullPath: '/buget-primarie/'
      preLoaderRoute: typeof BugetPrimarieIndexRouteImport
      parentRoute: typeof BugetPrimarieRouteRoute
    }
    '/research/employees-data': {
      id: '/research/employees-data'
      path: '/research/employees-data'
      fullPath: '/research/employees-data'
      preLoaderRoute: typeof ResearchEmployeesDataLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$code': {
      id: '/share/$code'
      path: '/share/$code'
      fullPath: '/share/$code'
      preLoaderRoute: typeof ShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$cui': {
      id: '/entities/$cui'
      path: '/entities/$cui'
      fullPath: '/entities/$cui'
      preLoaderRoute: typeof EntitiesCuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/new': {
      id: '/charts/new'
      path: '/charts/new'
      fullPath: '/charts/new'
      preLoaderRoute: typeof ChartsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id': {
      id: '/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie/forum': {
      id: '/buget-primarie/forum'
      path: '/forum'
      fullPath: '/buget-primarie/forum'
      preLoaderRoute: typeof BugetPrimarieForumRouteImport
      parentRoute: typeof BugetPrimarieRouteRoute
    }
    '/alerts/new': {
      id: '/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AlertsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId': {
      id: '/charts/$chartId'
      path: '/charts/$chartId'
      fullPath: '/charts/$chartId'
      preLoaderRoute: typeof ChartsChartIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie/$cui': {
      id: '/buget-primarie/$cui'
      path: '/$cui'
      fullPath: '/buget-primarie/$cui'
      preLoaderRoute: typeof BugetPrimarieCuiRouteRouteImport
      parentRoute: typeof BugetPrimarieRouteRoute
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/learning': {
      id: '/$lang/learning'
      path: '/$lang/learning'
      fullPath: '/$lang/learning'
      preLoaderRoute: typeof LangLearningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId/': {
      id: '/charts/$chartId/'
      path: '/'
      fullPath: '/charts/$chartId/'
      preLoaderRoute: typeof ChartsChartIdIndexLazyRouteImport
      parentRoute: typeof ChartsChartIdRouteRoute
    }
    '/alerts/$alertId/': {
      id: '/alerts/$alertId/'
      path: '/'
      fullPath: '/alerts/$alertId/'
      preLoaderRoute: typeof AlertsAlertIdIndexLazyRouteImport
      parentRoute: typeof AlertsAlertIdRouteRoute
    }
    '/maps/editor/': {
      id: '/maps/editor/'
      path: '/maps/editor'
      fullPath: '/maps/editor/'
      preLoaderRoute: typeof MapsEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/functional/': {
      id: '/classifications/functional/'
      path: '/classifications/functional'
      fullPath: '/classifications/functional/'
      preLoaderRoute: typeof ClassificationsFunctionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/': {
      id: '/classifications/economic/'
      path: '/classifications/economic'
      fullPath: '/classifications/economic/'
      preLoaderRoute: typeof ClassificationsEconomicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie/cauta/': {
      id: '/buget-primarie/cauta/'
      path: '/cauta'
      fullPath: '/buget-primarie/cauta/'
      preLoaderRoute: typeof BugetPrimarieCautaIndexRouteImport
      parentRoute: typeof BugetPrimarieRouteRoute
    }
    '/$lang/learning/': {
      id: '/$lang/learning/'
      path: '/'
      fullPath: '/$lang/learning/'
      preLoaderRoute: typeof LangLearningIndexRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/maps/public/$mapId': {
      id: '/maps/public/$mapId'
      path: '/maps/public/$mapId'
      fullPath: '/maps/public/$mapId'
      preLoaderRoute: typeof MapsPublicMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/editor/new': {
      id: '/maps/editor/new'
      path: '/maps/editor/new'
      fullPath: '/maps/editor/new'
      preLoaderRoute: typeof MapsEditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/editor/$mapId': {
      id: '/maps/editor/$mapId'
      path: '/maps/editor/$mapId'
      fullPath: '/maps/editor/$mapId'
      preLoaderRoute: typeof MapsEditorMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$cui/share-image.png': {
      id: '/entities/$cui/share-image.png'
      path: '/share-image.png'
      fullPath: '/entities/$cui/share-image.png'
      preLoaderRoute: typeof EntitiesCuiShareImageDotpngRouteImport
      parentRoute: typeof EntitiesCuiRoute
    }
    '/classifications/functional/$code': {
      id: '/classifications/functional/$code'
      path: '/classifications/functional/$code'
      fullPath: '/classifications/functional/$code'
      preLoaderRoute: typeof ClassificationsFunctionalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/$code': {
      id: '/classifications/economic/$code'
      path: '/classifications/economic/$code'
      fullPath: '/classifications/economic/$code'
      preLoaderRoute: typeof ClassificationsEconomicCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buget-primarie/$cui/primarie': {
      id: '/buget-primarie/$cui/primarie'
      path: '/primarie'
      fullPath: '/buget-primarie/$cui/primarie'
      preLoaderRoute: typeof BugetPrimarieCuiPrimarieRouteImport
      parentRoute: typeof BugetPrimarieCuiRouteRoute
    }
    '/buget-primarie/$cui/calendar': {
      id: '/buget-primarie/$cui/calendar'
      path: '/calendar'
      fullPath: '/buget-primarie/$cui/calendar'
      preLoaderRoute: typeof BugetPrimarieCuiCalendarRouteImport
      parentRoute: typeof BugetPrimarieCuiRouteRoute
    }
    '/$lang/learning/onboarding': {
      id: '/$lang/learning/onboarding'
      path: '/onboarding'
      fullPath: '/$lang/learning/onboarding'
      preLoaderRoute: typeof LangLearningOnboardingRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/buget-primarie/$cui/provocari': {
      id: '/buget-primarie/$cui/provocari'
      path: '/provocari'
      fullPath: '/buget-primarie/$cui/provocari'
      preLoaderRoute: typeof BugetPrimarieCuiProvocariRouteRouteImport
      parentRoute: typeof BugetPrimarieCuiRouteRoute
    }
    '/buget-primarie/cauta/harta/': {
      id: '/buget-primarie/cauta/harta/'
      path: '/cauta/harta'
      fullPath: '/buget-primarie/cauta/harta/'
      preLoaderRoute: typeof BugetPrimarieCautaHartaIndexRouteImport
      parentRoute: typeof BugetPrimarieRouteRoute
    }
    '/buget-primarie/$cui/provocari/': {
      id: '/buget-primarie/$cui/provocari/'
      path: '/'
      fullPath: '/buget-primarie/$cui/provocari/'
      preLoaderRoute: typeof BugetPrimarieCuiProvocariIndexRouteImport
      parentRoute: typeof BugetPrimarieCuiProvocariRouteRoute
    }
    '/$lang/learning/$pathId/': {
      id: '/$lang/learning/$pathId/'
      path: '/$pathId'
      fullPath: '/$lang/learning/$pathId/'
      preLoaderRoute: typeof LangLearningPathIdIndexRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/$lang/learning/certificates/$id': {
      id: '/$lang/learning/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/$lang/learning/certificates/$id'
      preLoaderRoute: typeof LangLearningCertificatesIdRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/buget-primarie/$cui/provocari/$moduleSlug/': {
      id: '/buget-primarie/$cui/provocari/$moduleSlug/'
      path: '/$moduleSlug'
      fullPath: '/buget-primarie/$cui/provocari/$moduleSlug/'
      preLoaderRoute: typeof BugetPrimarieCuiProvocariModuleSlugIndexRouteImport
      parentRoute: typeof BugetPrimarieCuiProvocariRouteRoute
    }
    '/$lang/learning/$pathId/$moduleId/$lessonId': {
      id: '/$lang/learning/$pathId/$moduleId/$lessonId'
      path: '/$pathId/$moduleId/$lessonId'
      fullPath: '/$lang/learning/$pathId/$moduleId/$lessonId'
      preLoaderRoute: typeof LangLearningPathIdModuleIdLessonIdRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug': {
      id: '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'
      path: '/$moduleSlug/$challengeSlug/$stepSlug'
      fullPath: '/buget-primarie/$cui/provocari/$moduleSlug/$challengeSlug/$stepSlug'
      preLoaderRoute: typeof BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRouteImport
      parentRoute: typeof BugetPrimarieCuiProvocariRouteRoute
    }
  }
}

interface BugetPrimarieCuiProvocariRouteRouteChildren {
  BugetPrimarieCuiProvocariIndexRoute: typeof BugetPrimarieCuiProvocariIndexRoute
  BugetPrimarieCuiProvocariModuleSlugIndexRoute: typeof BugetPrimarieCuiProvocariModuleSlugIndexRoute
  BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute: typeof BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute
}

const BugetPrimarieCuiProvocariRouteRouteChildren: BugetPrimarieCuiProvocariRouteRouteChildren =
  {
    BugetPrimarieCuiProvocariIndexRoute: BugetPrimarieCuiProvocariIndexRoute,
    BugetPrimarieCuiProvocariModuleSlugIndexRoute:
      BugetPrimarieCuiProvocariModuleSlugIndexRoute,
    BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute:
      BugetPrimarieCuiProvocariModuleSlugChallengeSlugStepSlugRoute,
  }

const BugetPrimarieCuiProvocariRouteRouteWithChildren =
  BugetPrimarieCuiProvocariRouteRoute._addFileChildren(
    BugetPrimarieCuiProvocariRouteRouteChildren,
  )

interface BugetPrimarieCuiRouteRouteChildren {
  BugetPrimarieCuiProvocariRouteRoute: typeof BugetPrimarieCuiProvocariRouteRouteWithChildren
  BugetPrimarieCuiCalendarRoute: typeof BugetPrimarieCuiCalendarRoute
  BugetPrimarieCuiPrimarieRoute: typeof BugetPrimarieCuiPrimarieRoute
}

const BugetPrimarieCuiRouteRouteChildren: BugetPrimarieCuiRouteRouteChildren = {
  BugetPrimarieCuiProvocariRouteRoute:
    BugetPrimarieCuiProvocariRouteRouteWithChildren,
  BugetPrimarieCuiCalendarRoute: BugetPrimarieCuiCalendarRoute,
  BugetPrimarieCuiPrimarieRoute: BugetPrimarieCuiPrimarieRoute,
}

const BugetPrimarieCuiRouteRouteWithChildren =
  BugetPrimarieCuiRouteRoute._addFileChildren(
    BugetPrimarieCuiRouteRouteChildren,
  )

interface BugetPrimarieRouteRouteChildren {
  BugetPrimarieCuiRouteRoute: typeof BugetPrimarieCuiRouteRouteWithChildren
  BugetPrimarieForumRoute: typeof BugetPrimarieForumRoute
  BugetPrimarieIndexRoute: typeof BugetPrimarieIndexRoute
  BugetPrimarieCautaIndexRoute: typeof BugetPrimarieCautaIndexRoute
  BugetPrimarieCautaHartaIndexRoute: typeof BugetPrimarieCautaHartaIndexRoute
}

const BugetPrimarieRouteRouteChildren: BugetPrimarieRouteRouteChildren = {
  BugetPrimarieCuiRouteRoute: BugetPrimarieCuiRouteRouteWithChildren,
  BugetPrimarieForumRoute: BugetPrimarieForumRoute,
  BugetPrimarieIndexRoute: BugetPrimarieIndexRoute,
  BugetPrimarieCautaIndexRoute: BugetPrimarieCautaIndexRoute,
  BugetPrimarieCautaHartaIndexRoute: BugetPrimarieCautaHartaIndexRoute,
}

const BugetPrimarieRouteRouteWithChildren =
  BugetPrimarieRouteRoute._addFileChildren(BugetPrimarieRouteRouteChildren)

interface LangLearningRouteRouteChildren {
  LangLearningOnboardingRoute: typeof LangLearningOnboardingRoute
  LangLearningIndexRoute: typeof LangLearningIndexRoute
  LangLearningCertificatesIdRoute: typeof LangLearningCertificatesIdRoute
  LangLearningPathIdIndexRoute: typeof LangLearningPathIdIndexRoute
  LangLearningPathIdModuleIdLessonIdRoute: typeof LangLearningPathIdModuleIdLessonIdRoute
}

const LangLearningRouteRouteChildren: LangLearningRouteRouteChildren = {
  LangLearningOnboardingRoute: LangLearningOnboardingRoute,
  LangLearningIndexRoute: LangLearningIndexRoute,
  LangLearningCertificatesIdRoute: LangLearningCertificatesIdRoute,
  LangLearningPathIdIndexRoute: LangLearningPathIdIndexRoute,
  LangLearningPathIdModuleIdLessonIdRoute:
    LangLearningPathIdModuleIdLessonIdRoute,
}

const LangLearningRouteRouteWithChildren =
  LangLearningRouteRoute._addFileChildren(LangLearningRouteRouteChildren)

interface AlertsAlertIdRouteRouteChildren {
  AlertsAlertIdIndexLazyRoute: typeof AlertsAlertIdIndexLazyRoute
}

const AlertsAlertIdRouteRouteChildren: AlertsAlertIdRouteRouteChildren = {
  AlertsAlertIdIndexLazyRoute: AlertsAlertIdIndexLazyRoute,
}

const AlertsAlertIdRouteRouteWithChildren =
  AlertsAlertIdRouteRoute._addFileChildren(AlertsAlertIdRouteRouteChildren)

interface ChartsChartIdRouteRouteChildren {
  ChartsChartIdIndexLazyRoute: typeof ChartsChartIdIndexLazyRoute
}

const ChartsChartIdRouteRouteChildren: ChartsChartIdRouteRouteChildren = {
  ChartsChartIdIndexLazyRoute: ChartsChartIdIndexLazyRoute,
}

const ChartsChartIdRouteRouteWithChildren =
  ChartsChartIdRouteRoute._addFileChildren(ChartsChartIdRouteRouteChildren)

interface EntitiesCuiRouteChildren {
  EntitiesCuiShareImageDotpngRoute: typeof EntitiesCuiShareImageDotpngRoute
}

const EntitiesCuiRouteChildren: EntitiesCuiRouteChildren = {
  EntitiesCuiShareImageDotpngRoute: EntitiesCuiShareImageDotpngRoute,
}

const EntitiesCuiRouteWithChildren = EntitiesCuiRoute._addFileChildren(
  EntitiesCuiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugetPrimarieRouteRoute: BugetPrimarieRouteRouteWithChildren,
  BudgetExplorerRoute: BudgetExplorerRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  EntityAnalyticsRoute: EntityAnalyticsRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  TestErrorRoute: TestErrorRoute,
  TermsLazyRoute: TermsLazyRoute,
  LangLearningRouteRoute: LangLearningRouteRouteWithChildren,
  AlertsAlertIdRouteRoute: AlertsAlertIdRouteRouteWithChildren,
  ChartsChartIdRouteRoute: ChartsChartIdRouteRouteWithChildren,
  AlertsNewRoute: AlertsNewRoute,
  CertificatesIdRoute: CertificatesIdRoute,
  ChartsNewRoute: ChartsNewRoute,
  EntitiesCuiRoute: EntitiesCuiRouteWithChildren,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ShareCodeRoute: ShareCodeRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ResearchEmployeesDataLazyRoute: ResearchEmployeesDataLazyRoute,
  ChartsIndexLazyRoute: ChartsIndexLazyRoute,
  ClassificationsEconomicCodeRoute: ClassificationsEconomicCodeRoute,
  ClassificationsFunctionalCodeRoute: ClassificationsFunctionalCodeRoute,
  MapsEditorMapIdRoute: MapsEditorMapIdRoute,
  MapsEditorNewRoute: MapsEditorNewRoute,
  MapsPublicMapIdRoute: MapsPublicMapIdRoute,
  ClassificationsEconomicIndexRoute: ClassificationsEconomicIndexRoute,
  ClassificationsFunctionalIndexRoute: ClassificationsFunctionalIndexRoute,
  MapsEditorIndexRoute: MapsEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
