/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as EntityAnalyticsRouteImport } from './routes/entity-analytics'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as BudgetExplorerRouteImport } from './routes/budget-explorer'
import { Route as BugeteLocale2026RouteRouteImport } from './routes/bugete-locale-2026/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugeteLocale2026IndexRouteImport } from './routes/bugete-locale-2026/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as ShareCodeRouteImport } from './routes/share.$code'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as ExperimentalMapRouteImport } from './routes/experimental/map'
import { Route as EntitiesCuiRouteImport } from './routes/entities.$cui'
import { Route as ChartsNewRouteImport } from './routes/charts/new'
import { Route as CertificatesIdRouteImport } from './routes/certificates.$id'
import { Route as BugeteLocale2026PrincipalRouteImport } from './routes/bugete-locale-2026/principal'
import { Route as BugeteLocale2026OnboardingRouteImport } from './routes/bugete-locale-2026/onboarding'
import { Route as BugeteLocale2026ForumRouteImport } from './routes/bugete-locale-2026/forum'
import { Route as AlertsNewRouteImport } from './routes/alerts/new'
import { Route as ChartsChartIdRouteRouteImport } from './routes/charts/$chartId/route'
import { Route as AlertsAlertIdRouteRouteImport } from './routes/alerts/$alertId/route'
import { Route as LangLearningRouteRouteImport } from './routes/$lang/learning/route'
import { Route as ClassificationsFunctionalIndexRouteImport } from './routes/classifications/functional/index'
import { Route as ClassificationsEconomicIndexRouteImport } from './routes/classifications/economic/index'
import { Route as BugeteLocale2026ChallengesIndexRouteImport } from './routes/bugete-locale-2026/challenges/index'
import { Route as BugeteLocale2026CautaIndexRouteImport } from './routes/bugete-locale-2026/cauta/index'
import { Route as LangLearningIndexRouteImport } from './routes/$lang/learning/index'
import { Route as EntitiesCuiShareImageDotpngRouteImport } from './routes/entities.$cui.share-image[.]png'
import { Route as ClassificationsFunctionalCodeRouteImport } from './routes/classifications/functional/$code'
import { Route as ClassificationsEconomicCodeRouteImport } from './routes/classifications/economic/$code'
import { Route as BugeteLocale2026ChallengesChallengeSlugRouteImport } from './routes/bugete-locale-2026/challenges/$challengeSlug'
import { Route as LangLearningOnboardingRouteImport } from './routes/$lang/learning/onboarding'
import { Route as BugeteLocale2026CautaHartaIndexRouteImport } from './routes/bugete-locale-2026/cauta/harta/index'
import { Route as LangLearningPathIdIndexRouteImport } from './routes/$lang/learning/$pathId/index'
import { Route as LangLearningCertificatesIdRouteImport } from './routes/$lang/learning/certificates.$id'
import { Route as LangLearningPathIdModuleIdLessonIdRouteImport } from './routes/$lang/learning/$pathId/$moduleId/$lessonId'

const TermsLazyRouteImport = createFileRoute('/terms')()
const ChartsIndexLazyRouteImport = createFileRoute('/charts/')()
const ResearchEmployeesDataLazyRouteImport = createFileRoute(
  '/research/employees-data',
)()
const ChartsChartIdIndexLazyRouteImport = createFileRoute('/charts/$chartId/')()
const AlertsAlertIdIndexLazyRouteImport = createFileRoute('/alerts/$alertId/')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))
const EntityAnalyticsRoute = EntityAnalyticsRouteImport.update({
  id: '/entity-analytics',
  path: '/entity-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/entity-analytics.lazy').then((d) => d.Route),
)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookie-policy.lazy').then((d) => d.Route))
const BudgetExplorerRoute = BudgetExplorerRouteImport.update({
  id: '/budget-explorer',
  path: '/budget-explorer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/budget-explorer.lazy').then((d) => d.Route),
)
const BugeteLocale2026RouteRoute = BugeteLocale2026RouteRouteImport.update({
  id: '/bugete-locale-2026',
  path: '/bugete-locale-2026',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/bugete-locale-2026/route.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIndexLazyRoute = ChartsIndexLazyRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts/index.lazy').then((d) => d.Route))
const BugeteLocale2026IndexRoute = BugeteLocale2026IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BugeteLocale2026RouteRoute,
} as any).lazy(() =>
  import('./routes/bugete-locale-2026/index.lazy').then((d) => d.Route),
)
const ResearchEmployeesDataLazyRoute =
  ResearchEmployeesDataLazyRouteImport.update({
    id: '/research/employees-data',
    path: '/research/employees-data',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/research/employees-data.lazy').then((d) => d.Route),
  )
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareCodeRoute = ShareCodeRouteImport.update({
  id: '/share/$code',
  path: '/share/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalMapRoute = ExperimentalMapRouteImport.update({
  id: '/experimental/map',
  path: '/experimental/map',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/experimental/map.lazy').then((d) => d.Route),
)
const EntitiesCuiRoute = EntitiesCuiRouteImport.update({
  id: '/entities/$cui',
  path: '/entities/$cui',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/entities.$cui.lazy').then((d) => d.Route))
const ChartsNewRoute = ChartsNewRouteImport.update({
  id: '/charts/new',
  path: '/charts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdRoute = CertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BugeteLocale2026PrincipalRoute =
  BugeteLocale2026PrincipalRouteImport.update({
    id: '/principal',
    path: '/principal',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/principal.lazy').then((d) => d.Route),
  )
const BugeteLocale2026OnboardingRoute =
  BugeteLocale2026OnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/onboarding.lazy').then((d) => d.Route),
  )
const BugeteLocale2026ForumRoute = BugeteLocale2026ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => BugeteLocale2026RouteRoute,
} as any).lazy(() =>
  import('./routes/bugete-locale-2026/forum.lazy').then((d) => d.Route),
)
const AlertsNewRoute = AlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerts/new.lazy').then((d) => d.Route))
const ChartsChartIdRouteRoute = ChartsChartIdRouteRouteImport.update({
  id: '/charts/$chartId',
  path: '/charts/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRouteRoute = AlertsAlertIdRouteRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLearningRouteRoute = LangLearningRouteRouteImport.update({
  id: '/$lang/learning',
  path: '/$lang/learning',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$lang/learning/route.lazy').then((d) => d.Route),
)
const ChartsChartIdIndexLazyRoute = ChartsChartIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartsChartIdRouteRoute,
} as any).lazy(() =>
  import('./routes/charts/$chartId/index.lazy').then((d) => d.Route),
)
const AlertsAlertIdIndexLazyRoute = AlertsAlertIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsAlertIdRouteRoute,
} as any).lazy(() =>
  import('./routes/alerts/$alertId/index.lazy').then((d) => d.Route),
)
const ClassificationsFunctionalIndexRoute =
  ClassificationsFunctionalIndexRouteImport.update({
    id: '/classifications/functional/',
    path: '/classifications/functional/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/index.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicIndexRoute =
  ClassificationsEconomicIndexRouteImport.update({
    id: '/classifications/economic/',
    path: '/classifications/economic/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/index.lazy').then((d) => d.Route),
  )
const BugeteLocale2026ChallengesIndexRoute =
  BugeteLocale2026ChallengesIndexRouteImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/challenges/index.lazy').then(
      (d) => d.Route,
    ),
  )
const BugeteLocale2026CautaIndexRoute =
  BugeteLocale2026CautaIndexRouteImport.update({
    id: '/cauta/',
    path: '/cauta/',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/cauta/index.lazy').then((d) => d.Route),
  )
const LangLearningIndexRoute = LangLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/index.lazy').then((d) => d.Route),
)
const EntitiesCuiShareImageDotpngRoute =
  EntitiesCuiShareImageDotpngRouteImport.update({
    id: '/share-image.png',
    path: '/share-image.png',
    getParentRoute: () => EntitiesCuiRoute,
  } as any)
const ClassificationsFunctionalCodeRoute =
  ClassificationsFunctionalCodeRouteImport.update({
    id: '/classifications/functional/$code',
    path: '/classifications/functional/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/functional/$code.lazy').then(
      (d) => d.Route,
    ),
  )
const ClassificationsEconomicCodeRoute =
  ClassificationsEconomicCodeRouteImport.update({
    id: '/classifications/economic/$code',
    path: '/classifications/economic/$code',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/classifications/economic/$code.lazy').then((d) => d.Route),
  )
const BugeteLocale2026ChallengesChallengeSlugRoute =
  BugeteLocale2026ChallengesChallengeSlugRouteImport.update({
    id: '/challenges/$challengeSlug',
    path: '/challenges/$challengeSlug',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/challenges/$challengeSlug.lazy').then(
      (d) => d.Route,
    ),
  )
const LangLearningOnboardingRoute = LangLearningOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/onboarding.lazy').then((d) => d.Route),
)
const BugeteLocale2026CautaHartaIndexRoute =
  BugeteLocale2026CautaHartaIndexRouteImport.update({
    id: '/cauta/harta/',
    path: '/cauta/harta/',
    getParentRoute: () => BugeteLocale2026RouteRoute,
  } as any).lazy(() =>
    import('./routes/bugete-locale-2026/cauta/harta/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LangLearningPathIdIndexRoute = LangLearningPathIdIndexRouteImport.update({
  id: '/$pathId/',
  path: '/$pathId/',
  getParentRoute: () => LangLearningRouteRoute,
} as any).lazy(() =>
  import('./routes/$lang/learning/$pathId/index.lazy').then((d) => d.Route),
)
const LangLearningCertificatesIdRoute =
  LangLearningCertificatesIdRouteImport.update({
    id: '/certificates/$id',
    path: '/certificates/$id',
    getParentRoute: () => LangLearningRouteRoute,
  } as any).lazy(() =>
    import('./routes/$lang/learning/certificates.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const LangLearningPathIdModuleIdLessonIdRoute =
  LangLearningPathIdModuleIdLessonIdRouteImport.update({
    id: '/$pathId/$moduleId/$lessonId',
    path: '/$pathId/$moduleId/$lessonId',
    getParentRoute: () => LangLearningRouteRoute,
  } as any).lazy(() =>
    import('./routes/$lang/learning/$pathId/$moduleId/$lessonId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bugete-locale-2026': typeof BugeteLocale2026RouteRouteWithChildren
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/$lang/learning': typeof LangLearningRouteRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/bugete-locale-2026/forum': typeof BugeteLocale2026ForumRoute
  '/bugete-locale-2026/onboarding': typeof BugeteLocale2026OnboardingRoute
  '/bugete-locale-2026/principal': typeof BugeteLocale2026PrincipalRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/experimental/map': typeof ExperimentalMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/bugete-locale-2026/': typeof BugeteLocale2026IndexRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/bugete-locale-2026/challenges/$challengeSlug': typeof BugeteLocale2026ChallengesChallengeSlugRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/$lang/learning/': typeof LangLearningIndexRoute
  '/bugete-locale-2026/cauta/': typeof BugeteLocale2026CautaIndexRoute
  '/bugete-locale-2026/challenges/': typeof BugeteLocale2026ChallengesIndexRoute
  '/classifications/economic/': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional/': typeof ClassificationsFunctionalIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId/': typeof LangLearningPathIdIndexRoute
  '/bugete-locale-2026/cauta/harta/': typeof BugeteLocale2026CautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/alerts/new': typeof AlertsNewRoute
  '/bugete-locale-2026/forum': typeof BugeteLocale2026ForumRoute
  '/bugete-locale-2026/onboarding': typeof BugeteLocale2026OnboardingRoute
  '/bugete-locale-2026/principal': typeof BugeteLocale2026PrincipalRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/experimental/map': typeof ExperimentalMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/bugete-locale-2026': typeof BugeteLocale2026IndexRoute
  '/charts': typeof ChartsIndexLazyRoute
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/bugete-locale-2026/challenges/$challengeSlug': typeof BugeteLocale2026ChallengesChallengeSlugRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/$lang/learning': typeof LangLearningIndexRoute
  '/bugete-locale-2026/cauta': typeof BugeteLocale2026CautaIndexRoute
  '/bugete-locale-2026/challenges': typeof BugeteLocale2026ChallengesIndexRoute
  '/classifications/economic': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional': typeof ClassificationsFunctionalIndexRoute
  '/alerts/$alertId': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId': typeof LangLearningPathIdIndexRoute
  '/bugete-locale-2026/cauta/harta': typeof BugeteLocale2026CautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bugete-locale-2026': typeof BugeteLocale2026RouteRouteWithChildren
  '/budget-explorer': typeof BudgetExplorerRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cookies': typeof CookiesRoute
  '/entity-analytics': typeof EntityAnalyticsRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/test-error': typeof TestErrorRoute
  '/terms': typeof TermsLazyRoute
  '/$lang/learning': typeof LangLearningRouteRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRouteRouteWithChildren
  '/charts/$chartId': typeof ChartsChartIdRouteRouteWithChildren
  '/alerts/new': typeof AlertsNewRoute
  '/bugete-locale-2026/forum': typeof BugeteLocale2026ForumRoute
  '/bugete-locale-2026/onboarding': typeof BugeteLocale2026OnboardingRoute
  '/bugete-locale-2026/principal': typeof BugeteLocale2026PrincipalRoute
  '/certificates/$id': typeof CertificatesIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/entities/$cui': typeof EntitiesCuiRouteWithChildren
  '/experimental/map': typeof ExperimentalMapRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/share/$code': typeof ShareCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/research/employees-data': typeof ResearchEmployeesDataLazyRoute
  '/bugete-locale-2026/': typeof BugeteLocale2026IndexRoute
  '/charts/': typeof ChartsIndexLazyRoute
  '/$lang/learning/onboarding': typeof LangLearningOnboardingRoute
  '/bugete-locale-2026/challenges/$challengeSlug': typeof BugeteLocale2026ChallengesChallengeSlugRoute
  '/classifications/economic/$code': typeof ClassificationsEconomicCodeRoute
  '/classifications/functional/$code': typeof ClassificationsFunctionalCodeRoute
  '/entities/$cui/share-image.png': typeof EntitiesCuiShareImageDotpngRoute
  '/$lang/learning/': typeof LangLearningIndexRoute
  '/bugete-locale-2026/cauta/': typeof BugeteLocale2026CautaIndexRoute
  '/bugete-locale-2026/challenges/': typeof BugeteLocale2026ChallengesIndexRoute
  '/classifications/economic/': typeof ClassificationsEconomicIndexRoute
  '/classifications/functional/': typeof ClassificationsFunctionalIndexRoute
  '/alerts/$alertId/': typeof AlertsAlertIdIndexLazyRoute
  '/charts/$chartId/': typeof ChartsChartIdIndexLazyRoute
  '/$lang/learning/certificates/$id': typeof LangLearningCertificatesIdRoute
  '/$lang/learning/$pathId/': typeof LangLearningPathIdIndexRoute
  '/bugete-locale-2026/cauta/harta/': typeof BugeteLocale2026CautaHartaIndexRoute
  '/$lang/learning/$pathId/$moduleId/$lessonId': typeof LangLearningPathIdModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bugete-locale-2026'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/$lang/learning'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/alerts/new'
    | '/bugete-locale-2026/forum'
    | '/bugete-locale-2026/onboarding'
    | '/bugete-locale-2026/principal'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/experimental/map'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/bugete-locale-2026/'
    | '/charts/'
    | '/$lang/learning/onboarding'
    | '/bugete-locale-2026/challenges/$challengeSlug'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/$lang/learning/'
    | '/bugete-locale-2026/cauta/'
    | '/bugete-locale-2026/challenges/'
    | '/classifications/economic/'
    | '/classifications/functional/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId/'
    | '/bugete-locale-2026/cauta/harta/'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/alerts/new'
    | '/bugete-locale-2026/forum'
    | '/bugete-locale-2026/onboarding'
    | '/bugete-locale-2026/principal'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/experimental/map'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/bugete-locale-2026'
    | '/charts'
    | '/$lang/learning/onboarding'
    | '/bugete-locale-2026/challenges/$challengeSlug'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/$lang/learning'
    | '/bugete-locale-2026/cauta'
    | '/bugete-locale-2026/challenges'
    | '/classifications/economic'
    | '/classifications/functional'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId'
    | '/bugete-locale-2026/cauta/harta'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/bugete-locale-2026'
    | '/budget-explorer'
    | '/cookie-policy'
    | '/cookies'
    | '/entity-analytics'
    | '/map'
    | '/privacy'
    | '/test-error'
    | '/terms'
    | '/$lang/learning'
    | '/alerts/$alertId'
    | '/charts/$chartId'
    | '/alerts/new'
    | '/bugete-locale-2026/forum'
    | '/bugete-locale-2026/onboarding'
    | '/bugete-locale-2026/principal'
    | '/certificates/$id'
    | '/charts/new'
    | '/entities/$cui'
    | '/experimental/map'
    | '/settings/notifications'
    | '/settings/profile'
    | '/share/$code'
    | '/unsubscribe/$token'
    | '/research/employees-data'
    | '/bugete-locale-2026/'
    | '/charts/'
    | '/$lang/learning/onboarding'
    | '/bugete-locale-2026/challenges/$challengeSlug'
    | '/classifications/economic/$code'
    | '/classifications/functional/$code'
    | '/entities/$cui/share-image.png'
    | '/$lang/learning/'
    | '/bugete-locale-2026/cauta/'
    | '/bugete-locale-2026/challenges/'
    | '/classifications/economic/'
    | '/classifications/functional/'
    | '/alerts/$alertId/'
    | '/charts/$chartId/'
    | '/$lang/learning/certificates/$id'
    | '/$lang/learning/$pathId/'
    | '/bugete-locale-2026/cauta/harta/'
    | '/$lang/learning/$pathId/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugeteLocale2026RouteRoute: typeof BugeteLocale2026RouteRouteWithChildren
  BudgetExplorerRoute: typeof BudgetExplorerRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CookiesRoute: typeof CookiesRoute
  EntityAnalyticsRoute: typeof EntityAnalyticsRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  TestErrorRoute: typeof TestErrorRoute
  TermsLazyRoute: typeof TermsLazyRoute
  LangLearningRouteRoute: typeof LangLearningRouteRouteWithChildren
  AlertsAlertIdRouteRoute: typeof AlertsAlertIdRouteRouteWithChildren
  ChartsChartIdRouteRoute: typeof ChartsChartIdRouteRouteWithChildren
  AlertsNewRoute: typeof AlertsNewRoute
  CertificatesIdRoute: typeof CertificatesIdRoute
  ChartsNewRoute: typeof ChartsNewRoute
  EntitiesCuiRoute: typeof EntitiesCuiRouteWithChildren
  ExperimentalMapRoute: typeof ExperimentalMapRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ShareCodeRoute: typeof ShareCodeRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ResearchEmployeesDataLazyRoute: typeof ResearchEmployeesDataLazyRoute
  ChartsIndexLazyRoute: typeof ChartsIndexLazyRoute
  ClassificationsEconomicCodeRoute: typeof ClassificationsEconomicCodeRoute
  ClassificationsFunctionalCodeRoute: typeof ClassificationsFunctionalCodeRoute
  ClassificationsEconomicIndexRoute: typeof ClassificationsEconomicIndexRoute
  ClassificationsFunctionalIndexRoute: typeof ClassificationsFunctionalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity-analytics': {
      id: '/entity-analytics'
      path: '/entity-analytics'
      fullPath: '/entity-analytics'
      preLoaderRoute: typeof EntityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-explorer': {
      id: '/budget-explorer'
      path: '/budget-explorer'
      fullPath: '/budget-explorer'
      preLoaderRoute: typeof BudgetExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugete-locale-2026': {
      id: '/bugete-locale-2026'
      path: '/bugete-locale-2026'
      fullPath: '/bugete-locale-2026'
      preLoaderRoute: typeof BugeteLocale2026RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugete-locale-2026/': {
      id: '/bugete-locale-2026/'
      path: '/'
      fullPath: '/bugete-locale-2026/'
      preLoaderRoute: typeof BugeteLocale2026IndexRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/research/employees-data': {
      id: '/research/employees-data'
      path: '/research/employees-data'
      fullPath: '/research/employees-data'
      preLoaderRoute: typeof ResearchEmployeesDataLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$code': {
      id: '/share/$code'
      path: '/share/$code'
      fullPath: '/share/$code'
      preLoaderRoute: typeof ShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental/map': {
      id: '/experimental/map'
      path: '/experimental/map'
      fullPath: '/experimental/map'
      preLoaderRoute: typeof ExperimentalMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$cui': {
      id: '/entities/$cui'
      path: '/entities/$cui'
      fullPath: '/entities/$cui'
      preLoaderRoute: typeof EntitiesCuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/new': {
      id: '/charts/new'
      path: '/charts/new'
      fullPath: '/charts/new'
      preLoaderRoute: typeof ChartsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id': {
      id: '/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugete-locale-2026/principal': {
      id: '/bugete-locale-2026/principal'
      path: '/principal'
      fullPath: '/bugete-locale-2026/principal'
      preLoaderRoute: typeof BugeteLocale2026PrincipalRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/bugete-locale-2026/onboarding': {
      id: '/bugete-locale-2026/onboarding'
      path: '/onboarding'
      fullPath: '/bugete-locale-2026/onboarding'
      preLoaderRoute: typeof BugeteLocale2026OnboardingRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/bugete-locale-2026/forum': {
      id: '/bugete-locale-2026/forum'
      path: '/forum'
      fullPath: '/bugete-locale-2026/forum'
      preLoaderRoute: typeof BugeteLocale2026ForumRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/alerts/new': {
      id: '/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AlertsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId': {
      id: '/charts/$chartId'
      path: '/charts/$chartId'
      fullPath: '/charts/$chartId'
      preLoaderRoute: typeof ChartsChartIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/learning': {
      id: '/$lang/learning'
      path: '/$lang/learning'
      fullPath: '/$lang/learning'
      preLoaderRoute: typeof LangLearningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId/': {
      id: '/charts/$chartId/'
      path: '/'
      fullPath: '/charts/$chartId/'
      preLoaderRoute: typeof ChartsChartIdIndexLazyRouteImport
      parentRoute: typeof ChartsChartIdRouteRoute
    }
    '/alerts/$alertId/': {
      id: '/alerts/$alertId/'
      path: '/'
      fullPath: '/alerts/$alertId/'
      preLoaderRoute: typeof AlertsAlertIdIndexLazyRouteImport
      parentRoute: typeof AlertsAlertIdRouteRoute
    }
    '/classifications/functional/': {
      id: '/classifications/functional/'
      path: '/classifications/functional'
      fullPath: '/classifications/functional/'
      preLoaderRoute: typeof ClassificationsFunctionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/': {
      id: '/classifications/economic/'
      path: '/classifications/economic'
      fullPath: '/classifications/economic/'
      preLoaderRoute: typeof ClassificationsEconomicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugete-locale-2026/challenges/': {
      id: '/bugete-locale-2026/challenges/'
      path: '/challenges'
      fullPath: '/bugete-locale-2026/challenges/'
      preLoaderRoute: typeof BugeteLocale2026ChallengesIndexRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/bugete-locale-2026/cauta/': {
      id: '/bugete-locale-2026/cauta/'
      path: '/cauta'
      fullPath: '/bugete-locale-2026/cauta/'
      preLoaderRoute: typeof BugeteLocale2026CautaIndexRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/$lang/learning/': {
      id: '/$lang/learning/'
      path: '/'
      fullPath: '/$lang/learning/'
      preLoaderRoute: typeof LangLearningIndexRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/entities/$cui/share-image.png': {
      id: '/entities/$cui/share-image.png'
      path: '/share-image.png'
      fullPath: '/entities/$cui/share-image.png'
      preLoaderRoute: typeof EntitiesCuiShareImageDotpngRouteImport
      parentRoute: typeof EntitiesCuiRoute
    }
    '/classifications/functional/$code': {
      id: '/classifications/functional/$code'
      path: '/classifications/functional/$code'
      fullPath: '/classifications/functional/$code'
      preLoaderRoute: typeof ClassificationsFunctionalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifications/economic/$code': {
      id: '/classifications/economic/$code'
      path: '/classifications/economic/$code'
      fullPath: '/classifications/economic/$code'
      preLoaderRoute: typeof ClassificationsEconomicCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugete-locale-2026/challenges/$challengeSlug': {
      id: '/bugete-locale-2026/challenges/$challengeSlug'
      path: '/challenges/$challengeSlug'
      fullPath: '/bugete-locale-2026/challenges/$challengeSlug'
      preLoaderRoute: typeof BugeteLocale2026ChallengesChallengeSlugRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/$lang/learning/onboarding': {
      id: '/$lang/learning/onboarding'
      path: '/onboarding'
      fullPath: '/$lang/learning/onboarding'
      preLoaderRoute: typeof LangLearningOnboardingRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/bugete-locale-2026/cauta/harta/': {
      id: '/bugete-locale-2026/cauta/harta/'
      path: '/cauta/harta'
      fullPath: '/bugete-locale-2026/cauta/harta/'
      preLoaderRoute: typeof BugeteLocale2026CautaHartaIndexRouteImport
      parentRoute: typeof BugeteLocale2026RouteRoute
    }
    '/$lang/learning/$pathId/': {
      id: '/$lang/learning/$pathId/'
      path: '/$pathId'
      fullPath: '/$lang/learning/$pathId/'
      preLoaderRoute: typeof LangLearningPathIdIndexRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/$lang/learning/certificates/$id': {
      id: '/$lang/learning/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/$lang/learning/certificates/$id'
      preLoaderRoute: typeof LangLearningCertificatesIdRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
    '/$lang/learning/$pathId/$moduleId/$lessonId': {
      id: '/$lang/learning/$pathId/$moduleId/$lessonId'
      path: '/$pathId/$moduleId/$lessonId'
      fullPath: '/$lang/learning/$pathId/$moduleId/$lessonId'
      preLoaderRoute: typeof LangLearningPathIdModuleIdLessonIdRouteImport
      parentRoute: typeof LangLearningRouteRoute
    }
  }
}

interface BugeteLocale2026RouteRouteChildren {
  BugeteLocale2026ForumRoute: typeof BugeteLocale2026ForumRoute
  BugeteLocale2026OnboardingRoute: typeof BugeteLocale2026OnboardingRoute
  BugeteLocale2026PrincipalRoute: typeof BugeteLocale2026PrincipalRoute
  BugeteLocale2026IndexRoute: typeof BugeteLocale2026IndexRoute
  BugeteLocale2026ChallengesChallengeSlugRoute: typeof BugeteLocale2026ChallengesChallengeSlugRoute
  BugeteLocale2026CautaIndexRoute: typeof BugeteLocale2026CautaIndexRoute
  BugeteLocale2026ChallengesIndexRoute: typeof BugeteLocale2026ChallengesIndexRoute
  BugeteLocale2026CautaHartaIndexRoute: typeof BugeteLocale2026CautaHartaIndexRoute
}

const BugeteLocale2026RouteRouteChildren: BugeteLocale2026RouteRouteChildren = {
  BugeteLocale2026ForumRoute: BugeteLocale2026ForumRoute,
  BugeteLocale2026OnboardingRoute: BugeteLocale2026OnboardingRoute,
  BugeteLocale2026PrincipalRoute: BugeteLocale2026PrincipalRoute,
  BugeteLocale2026IndexRoute: BugeteLocale2026IndexRoute,
  BugeteLocale2026ChallengesChallengeSlugRoute:
    BugeteLocale2026ChallengesChallengeSlugRoute,
  BugeteLocale2026CautaIndexRoute: BugeteLocale2026CautaIndexRoute,
  BugeteLocale2026ChallengesIndexRoute: BugeteLocale2026ChallengesIndexRoute,
  BugeteLocale2026CautaHartaIndexRoute: BugeteLocale2026CautaHartaIndexRoute,
}

const BugeteLocale2026RouteRouteWithChildren =
  BugeteLocale2026RouteRoute._addFileChildren(
    BugeteLocale2026RouteRouteChildren,
  )

interface LangLearningRouteRouteChildren {
  LangLearningOnboardingRoute: typeof LangLearningOnboardingRoute
  LangLearningIndexRoute: typeof LangLearningIndexRoute
  LangLearningCertificatesIdRoute: typeof LangLearningCertificatesIdRoute
  LangLearningPathIdIndexRoute: typeof LangLearningPathIdIndexRoute
  LangLearningPathIdModuleIdLessonIdRoute: typeof LangLearningPathIdModuleIdLessonIdRoute
}

const LangLearningRouteRouteChildren: LangLearningRouteRouteChildren = {
  LangLearningOnboardingRoute: LangLearningOnboardingRoute,
  LangLearningIndexRoute: LangLearningIndexRoute,
  LangLearningCertificatesIdRoute: LangLearningCertificatesIdRoute,
  LangLearningPathIdIndexRoute: LangLearningPathIdIndexRoute,
  LangLearningPathIdModuleIdLessonIdRoute:
    LangLearningPathIdModuleIdLessonIdRoute,
}

const LangLearningRouteRouteWithChildren =
  LangLearningRouteRoute._addFileChildren(LangLearningRouteRouteChildren)

interface AlertsAlertIdRouteRouteChildren {
  AlertsAlertIdIndexLazyRoute: typeof AlertsAlertIdIndexLazyRoute
}

const AlertsAlertIdRouteRouteChildren: AlertsAlertIdRouteRouteChildren = {
  AlertsAlertIdIndexLazyRoute: AlertsAlertIdIndexLazyRoute,
}

const AlertsAlertIdRouteRouteWithChildren =
  AlertsAlertIdRouteRoute._addFileChildren(AlertsAlertIdRouteRouteChildren)

interface ChartsChartIdRouteRouteChildren {
  ChartsChartIdIndexLazyRoute: typeof ChartsChartIdIndexLazyRoute
}

const ChartsChartIdRouteRouteChildren: ChartsChartIdRouteRouteChildren = {
  ChartsChartIdIndexLazyRoute: ChartsChartIdIndexLazyRoute,
}

const ChartsChartIdRouteRouteWithChildren =
  ChartsChartIdRouteRoute._addFileChildren(ChartsChartIdRouteRouteChildren)

interface EntitiesCuiRouteChildren {
  EntitiesCuiShareImageDotpngRoute: typeof EntitiesCuiShareImageDotpngRoute
}

const EntitiesCuiRouteChildren: EntitiesCuiRouteChildren = {
  EntitiesCuiShareImageDotpngRoute: EntitiesCuiShareImageDotpngRoute,
}

const EntitiesCuiRouteWithChildren = EntitiesCuiRoute._addFileChildren(
  EntitiesCuiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugeteLocale2026RouteRoute: BugeteLocale2026RouteRouteWithChildren,
  BudgetExplorerRoute: BudgetExplorerRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CookiesRoute: CookiesRoute,
  EntityAnalyticsRoute: EntityAnalyticsRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  TestErrorRoute: TestErrorRoute,
  TermsLazyRoute: TermsLazyRoute,
  LangLearningRouteRoute: LangLearningRouteRouteWithChildren,
  AlertsAlertIdRouteRoute: AlertsAlertIdRouteRouteWithChildren,
  ChartsChartIdRouteRoute: ChartsChartIdRouteRouteWithChildren,
  AlertsNewRoute: AlertsNewRoute,
  CertificatesIdRoute: CertificatesIdRoute,
  ChartsNewRoute: ChartsNewRoute,
  EntitiesCuiRoute: EntitiesCuiRouteWithChildren,
  ExperimentalMapRoute: ExperimentalMapRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ShareCodeRoute: ShareCodeRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ResearchEmployeesDataLazyRoute: ResearchEmployeesDataLazyRoute,
  ChartsIndexLazyRoute: ChartsIndexLazyRoute,
  ClassificationsEconomicCodeRoute: ClassificationsEconomicCodeRoute,
  ClassificationsFunctionalCodeRoute: ClassificationsFunctionalCodeRoute,
  ClassificationsEconomicIndexRoute: ClassificationsEconomicIndexRoute,
  ClassificationsFunctionalIndexRoute: ClassificationsFunctionalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
